fastlane/metadata/android/fr-FR/full_description.txt
fastlane/metadata/android/fr-FR/short_description.txt

Here's my modest contribution to OpenTracks

Added French translation for F-Droid

---

src/androidTest/java/de/dennisguse/opentracks/fragments/ChartFragmentTest.java
src/main/java/de/dennisguse/opentracks/TrackDetailActivity.java
src/main/java/de/dennisguse/opentracks/fragments/ChartDistanceFragment.java
src/main/java/de/dennisguse/opentracks/fragments/ChartFragment.java
src/main/java/de/dennisguse/opentracks/fragments/ChartTimeFragment.java
src/main/java/de/dennisguse/opentracks/fragments/ConfirmDeleteDialogFragment.java
src/main/java/de/dennisguse/opentracks/fragments/DeleteMarkerDialogFragment.java
src/main/java/de/dennisguse/opentracks/fragments/FileTypeDialogFragment.java
src/main/java/de/dennisguse/opentracks/fragments/MarkerDetailFragment.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/ExportAsyncTask.java

Fixes #127.

---

src/androidTest/java/de/dennisguse/opentracks/content/provider/CustomContentProviderTest.java
src/androidTest/java/de/dennisguse/opentracks/content/provider/CustomContentProviderUtilsTest.java
src/main/java/de/dennisguse/opentracks/content/DataSourceManager.java
src/main/java/de/dennisguse/opentracks/content/data/TrackPointsColumns.java
src/main/java/de/dennisguse/opentracks/content/provider/ContentProviderUtils.java
src/main/java/de/dennisguse/opentracks/content/provider/CustomContentProvider.java
src/main/java/de/dennisguse/opentracks/util/IntentDashboardUtils.java

TrackPoint by TrackId was not working (and not used).

Bugfix: match internal ContentURI correctly.

---

README_DEVELOPER.md
src/androidTest/java/de/dennisguse/opentracks/content/provider/CustomContentProviderUtilsTest.java
src/main/java/de/dennisguse/opentracks/content/provider/ContentProviderUtils.java
src/main/java/de/dennisguse/opentracks/content/provider/CustomContentProvider.java
src/main/java/de/dennisguse/opentracks/util/IntentDashboardUtils.java
src/main/java/de/dennisguse/opentracks/util/IntentUtils.java

Forward a list of track IDs to the dashboard. Uri's would look like this `content://de.dennisguse.opentracks.debug.content/trackpoints/62,63,64`

Forward multiple tracks to dashboard

---

src/main/res/menu/list_context_menu.xml

Unify order of show on map and share menu entries.

---

src/main/java/de/dennisguse/opentracks/MarkerEditActivity.java
src/main/java/de/dennisguse/opentracks/TrackDetailActivity.java
src/main/java/de/dennisguse/opentracks/util/FileUtils.java
src/main/res/drawable/ic_add_a_photo_24dp.xml
src/main/res/drawable/ic_add_photo_alternate_24dp.xml
src/main/res/drawable/shape_circle_darkgray.xml
src/main/res/layout/marker_edit.xml
src/main/res/menu/marker_edit.xml
src/main/res/menu/track_detail.xml
src/main/res/values-b+es+419/strings.xml
src/main/res/values-es/strings.xml
src/main/res/values/strings.xml

~~Now, when user click on "Insert Photo" option the app ask to the user what to do: take a photo or select an image from the Gallery~~ Now user can use a new option (Insert gallery image) to create a waypoint with a gallery image. Also, It's not necessary Storage permission because I have used SAF (Storage Access Framework).
I have done the same you can see here: https://medium.com/@pednekarshashank33/android-10s-scoped-storage-image-picker-gallery-camera-d3dcca427bbf
I have tested it on a virtual device and on my Pixel XL 2.
https://github.com/OpenTracksApp/OpenTracks/issues/122
**Link to the APK**
I have uploaded the APK to my nextcloud:
https://ppp.woelkli.com/s/JMxJ6tHXB9wXN6c
password for download: OpenTracks122
**License …

Myissue122

---

src/androidTest/java/de/dennisguse/opentracks/content/provider/CustomContentProviderTest.java
src/androidTest/java/de/dennisguse/opentracks/content/provider/CustomSQLiteOpenHelperTest.java
src/main/java/de/dennisguse/opentracks/MarkerListActivity.java
src/main/java/de/dennisguse/opentracks/content/data/TrackPointsColumns.java
src/main/java/de/dennisguse/opentracks/content/data/TracksColumns.java
src/main/java/de/dennisguse/opentracks/content/data/WaypointsColumns.java
src/main/java/de/dennisguse/opentracks/content/provider/ContentProviderUtils.java
src/main/java/de/dennisguse/opentracks/content/provider/CustomSQLiteOpenHelper.java
src/main/java/de/dennisguse/opentracks/stats/TripStatistics.java

These changes modify the underlying database structure (via upgrade/downgrade):
* remove unused columns
* add indices.
Testing of schema changes is done on an empty database (without any data).
This includes upgrading from initial database version (23) to most recent (25) as well as downgrade to 23.
Test code will also work for further changes and requiring that database creation as well as upgrade/downgrade lead to identical results.
i did not measure if the performance changed due to adding indices.

Database cleanup and optimization

---

src/main/java/de/dennisguse/opentracks/TrackDetailActivity.java
src/main/java/de/dennisguse/opentracks/TrackListActivity.java
src/main/java/de/dennisguse/opentracks/fragments/StatsFragment.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingService.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingServiceBinder.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingServiceInterface.java
src/main/java/de/dennisguse/opentracks/stats/TripStatisticsUpdater.java
src/main/res/drawable/ic_play_circle_24dp.xml
src/main/res/menu/track_detail.xml
src/main/res/values-b+es+419/strings.xml
src/main/res/values-es/strings.xml
src/main/res/values/strings.xml

TrackDetailActivity starts an actual recording.
Also, from TrackDetailActivity menu you can resume the track you are seeing.
Possibly there are things to improve :D
#103 
#11 

TrackDetailActivity starts an actual recording and a stopped recording can be resumed. Fixes #103 and #11

---

src/main/java/de/dennisguse/opentracks/services/TrackRecordingService.java

Resume track option creates a segment like in pause/continue.
Improves #103 and #11

Resume track: creates a segment like pause/continue

---

src/main/java/de/dennisguse/opentracks/io/file/importer/AbstractFileTrackImporter.java

@dennisguse in the cherry pick process in PR #178 we added a bug. It's now fixed.
I think a new version 3.6.1 is necessary due to the importance of this failure, isn't it?
#183 

URIs for waypoint's photos are correct. Fixes #183.

---

src/androidTest/java/de/dennisguse/opentracks/TrackStubUtils.java
src/androidTest/java/de/dennisguse/opentracks/content/data/TestDataUtil.java
src/androidTest/java/de/dennisguse/opentracks/content/provider/CustomContentProviderUtilsTest.java
src/androidTest/java/de/dennisguse/opentracks/io/file/importer/AbstractTestFileTrackImporter.java
src/androidTest/java/de/dennisguse/opentracks/io/file/importer/ExportImportTest.java
src/androidTest/java/de/dennisguse/opentracks/io/file/importer/GpxFileTrackImporterTest.java
src/androidTest/java/de/dennisguse/opentracks/io/file/importer/KmlFileTrackImporterTest.java
src/androidTest/java/de/dennisguse/opentracks/services/TrackRecordingServiceTest.java
src/androidTest/java/de/dennisguse/opentracks/services/TrackRecordingServiceTestLocation.java
src/main/java/de/dennisguse/opentracks/content/data/Track.java
src/main/java/de/dennisguse/opentracks/content/data/TrackPoint.java
src/main/java/de/dennisguse/opentracks/content/data/Waypoint.java
src/main/java/de/dennisguse/opentracks/content/provider/ContentProviderUtils.java
src/main/java/de/dennisguse/opentracks/content/sensor/SensorDataSet.java
src/main/java/de/dennisguse/opentracks/fragments/StatsFragment.java
src/main/java/de/dennisguse/opentracks/io/file/importer/AbstractFileTrackImporter.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingService.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingServiceBinder.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingServiceInterface.java
src/main/java/de/dennisguse/opentracks/stats/TrackStatisticsUpdater.java
src/main/java/de/dennisguse/opentracks/util/LocationUtils.java
src/main/java/de/dennisguse/opentracks/util/TrackPointUtils.java

Refactoring of how the TrackRecordingSerivce handles inserting of locations from LocationManager.
Also added tests to keep everything in place.
Necessary for #10.

Cleanup of TrackRecordingService

---

src/main/java/de/dennisguse/opentracks/fragments/ChartFragment.java
src/main/java/de/dennisguse/opentracks/fragments/StatsFragment.java
src/main/java/de/dennisguse/opentracks/services/tasks/AnnouncementPeriodicTask.java
src/main/java/de/dennisguse/opentracks/util/AnnouncementUtils.java
src/main/java/de/dennisguse/opentracks/util/PreferencesUtils.java
src/main/java/de/dennisguse/opentracks/util/TrackIconUtils.java
src/main/res/values-b+es+419/strings.xml
src/main/res/values-ca/strings.xml
src/main/res/values/settings.xml
src/main/res/values/strings.xml

I've been merge issue#155 onto master.

Merge issue#151

---

src/main/java/de/dennisguse/opentracks/util/DialogUtils.java
src/main/res/values/styles_custom.xml
src/main/res/values/themes_custom.xml

Adding indeterminateTintMode="src_in"
I have found there is a compatibility issue in styles_custom.xml. You forget to add `android:indeterminateTintMode="src_in"`, which can cause the color of ProgressBar not consistent when API Level < 23. This pull request help fix this issue.

Fix compatibility issue in styles_custom.xml

---

src/main/java/de/dennisguse/opentracks/TrackDetailActivity.java
src/main/java/de/dennisguse/opentracks/TrackListActivity.java

I've fixed the #200 
Only starts a new record if "someone" request it (resume track option is clicked or record button is clicked).
#200 

Manually starting GPS and opening a recorded track bug fixed. Fixes #200.

---

build.gradle
doc/activities.txt
src/main/AndroidManifest.xml
src/main/java/de/dennisguse/opentracks/AbstractListActivity.java
src/main/java/de/dennisguse/opentracks/SearchListActivity.java
src/main/java/de/dennisguse/opentracks/TrackActivityDataHubInterface.java
src/main/java/de/dennisguse/opentracks/TrackListActivity.java
src/main/java/de/dennisguse/opentracks/TrackRecordedActivity.java
src/main/java/de/dennisguse/opentracks/TrackRecordingActivity.java
src/main/java/de/dennisguse/opentracks/fragments/ChartFragment.java
src/main/java/de/dennisguse/opentracks/fragments/StatisticsRecordedFragment.java
src/main/java/de/dennisguse/opentracks/fragments/StatisticsRecordingFragment.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingService.java
src/main/res/layout/statistics_recorded.xml
src/main/res/layout/statistics_recording.xml
src/main/res/layout/track_record.xml
src/main/res/menu/track_record.xml
src/main/res/values/strings.xml
src/main/res/values/styles.xml

- I've split TrackDetailActivity into TrackDetailActivity and TrackRecordActivity.
- I've split StatsFragment into StatsDetailFragment and StatsRecordFragment.
- Both activities share the same ChartFragment because there aren't any difference between detail and record (both use TrackDataHub to feed the charts).
Theses changes simplify the menu logic and record/resume logic. Also, you can create different layouts for recording and detail.
**I've added the datetime of the activity in the Detail layout**. I like to know when I record an activity so i think is useful to put it in the detail. Anyway I can remove it :sweat_smile:
#171 

Split detail and record to simplify the code.

---

src/main/java/de/dennisguse/opentracks/util/IntentDashboardUtils.java

Needed for: https://github.com/OpenTracksApp/OSMDashboard/pull/38

forward keep screen on while recording preference to dashboard

---

doc/activities.txt
src/main/java/de/dennisguse/opentracks/AggregatedStatisticsActivity.java
src/main/res/layout/aggregated_stats.xml
src/main/res/values/strings.xml

Fixed https://github.com/OpenTracksApp/OpenTracks/issues/295

Aggregated statistics: updated PlantUML and handle empty list.

---

src/androidTest/java/de/dennisguse/opentracks/content/provider/CustomContentProviderUtilsTest.java
src/androidTest/java/de/dennisguse/opentracks/content/provider/CustomSQLiteOpenHelperTest.java
src/androidTest/java/de/dennisguse/opentracks/util/UUIDUtilsTest.java
src/main/java/de/dennisguse/opentracks/content/data/Track.java
src/main/java/de/dennisguse/opentracks/content/data/TracksColumns.java
src/main/java/de/dennisguse/opentracks/content/provider/ContentProviderUtils.java
src/main/java/de/dennisguse/opentracks/content/provider/CustomSQLiteOpenHelper.java
src/main/java/de/dennisguse/opentracks/util/UUIDUtils.java

Adds UUID to `Track` and stores it in Tracks-table.
Includes database migration for existing tracks (generates a new random UUID).
Export and import of the UUID still needs to be done.

Generate UUID for each track (necessary for synchronization).

---

src/main/AndroidManifest.xml
src/main/java/de/dennisguse/opentracks/TrackController.java
src/main/java/de/dennisguse/opentracks/TrackRecordingActivity.java
src/main/res/layout-land/track_record.xml

Enabled landscape mode for all activities.
TrackRecordingActivity: restore state from savedBundle rather than using two trackIds.
Removed recording started toast message.

Landscape#32

---

drawable-svg/ic_marker_orange_pushpin_with_shadow.svg

@dennisguse asked for an orange pushpin
#115 
As before: cc0 for this graphic.

Added an orange version of the ic_marker pushpin

---

src/androidTest/java/de/dennisguse/opentracks/services/AdaptiveLocationListenerPolicyTest.java
src/androidTest/java/de/dennisguse/opentracks/services/TrackRecordingServiceTest.java
src/androidTest/java/de/dennisguse/opentracks/services/TrackRecordingServiceTestLocation.java
src/androidTest/java/de/dennisguse/opentracks/services/TrackRecordingServiceTestLooper.java
src/androidTest/java/de/dennisguse/opentracks/services/handlers/LocationHandlerTest.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingService.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingServiceBinder.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingServiceInterface.java
src/main/java/de/dennisguse/opentracks/services/handlers/AbsoluteLocationListenerPolicy.java
src/main/java/de/dennisguse/opentracks/services/handlers/AdaptiveLocationListenerPolicy.java
src/main/java/de/dennisguse/opentracks/services/handlers/HandlerServer.java
src/main/java/de/dennisguse/opentracks/services/handlers/LocationHandler.java
src/main/java/de/dennisguse/opentracks/services/handlers/LocationListenerPolicy.java

Restructuring TrackRecordingService.
The idea was original discussed in #246 where there is useful information.
The main idea is that TrackRecordingService only manages the lifetime of different handlers.

Restructuring TrackRecordingService

---

src/main/AndroidManifest.xml
src/main/java/de/dennisguse/opentracks/fragments/ImportProgressDialogFragment.java
src/main/java/de/dennisguse/opentracks/io/file/importer/DirectoryChooserActivity.java
src/main/java/de/dennisguse/opentracks/io/file/importer/ImportActivity.java
src/main/java/de/dennisguse/opentracks/util/FileUtils.java

Now import of individual files can be triggered via file managers.
It is better for testing...

Import via intent

---

src/main/java/de/dennisguse/opentracks/MarkerEditActivity.java
src/main/java/de/dennisguse/opentracks/content/data/Waypoint.java

Fixes NPE (#325)

---

src/main/java/de/dennisguse/opentracks/MarkerEditActivity.java

On activity restart, the old waypoint photouri was overwriting, the new one (that was restored from the bundle).
@pstorch Nice catch ;)

MarkerEditActivity: do not overwrite new photoUri with previous one.

---

src/main/AndroidManifest.xml

Fixed too optimistic intent-filter for imports.

---

src/main/java/de/dennisguse/opentracks/TrackListActivity.java
src/main/java/de/dennisguse/opentracks/TrackRecordedActivity.java
src/main/java/de/dennisguse/opentracks/TrackRecordingActivity.java
src/main/java/de/dennisguse/opentracks/util/IntentDashboardUtils.java
src/main/java/de/dennisguse/opentracks/util/PreferencesUtils.java
src/main/res/values/settings.xml
src/main/res/values/strings.xml
src/main/res/xml/settings.xml

... setting is also provided via Dashboard API.
@pstorch What do you think, makes this feature sense for OSMDashboard?

TrackRecordingActivity: added setting for fullscreen.

---

src/main/java/de/dennisguse/opentracks/settings/SettingsActivity.java
src/main/res/values-cs/strings.xml
src/main/res/values-da/strings.xml
src/main/res/values-de/strings.xml
src/main/res/values-es/strings.xml
src/main/res/values-et/strings.xml
src/main/res/values-eu/strings.xml
src/main/res/values-fi/strings.xml
src/main/res/values-fr/strings.xml
src/main/res/values-gl/strings.xml
src/main/res/values-nl/strings.xml
src/main/res/values/settings.xml
src/main/res/values/strings.xml
src/main/res/xml/settings.xml

Wheel circumference is now a textfield accepting input as mm.

---

src/androidTest/java/de/dennisguse/opentracks/io/file/importer/ExportImportTest.java
src/main/java/de/dennisguse/opentracks/content/provider/ShareContentProvider.java
src/main/java/de/dennisguse/opentracks/fragments/ExportProgressDialogFragment.java
src/main/java/de/dennisguse/opentracks/io/file/TrackFileFormat.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/FileTrackExporter.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/GpxTrackWriter.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/KmlTrackWriter.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/KmzTrackExporter.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/TrackExporter.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/TrackWriter.java

exporter refactoring as foundation to https://github.com/OpenTracksApp/OpenTracks/pull/378

Refactor exporter

---

src/main/java/de/dennisguse/opentracks/services/handlers/GpsStatus.java

Checking gps status out in a old smartphone I found two bugs:
- Bugfix 1: race condition issue fixed with a flag:
LocationHandler could call GpsStstatus multiple times and before GpsStatus could check the status.
- Bugfix 2: location time issue fixed setting the time every time a location is received:
Altough GpsStatus was called every second GpsStatus returned a bad gps signal because time diff between locations was about 14 seconds or more according to some tests in a smartphone.
**Testing**
I tested this PR with 4 phones (including the one with before errors) and the 4 ones work like a charm:
- Pixel 2 XL with Lineage 17.1
- Pixel 3a with Android 10.
- Huawei P20 Lite with Android 9.
- Sony Xperia XZ1 Compact with Lineage 16.2 (It's the one to blame for …

Gps Status: bugfixes.

---

src/main/java/de/dennisguse/opentracks/TrackController.java
src/main/res/drawable/ic_button_stop_anim.xml

Discovered in #390 for devices with API Level 25. Not fixing the initial issue, but should be corrected as well.

Fix force close on stop button for older devices

---

build.gradle
fastlane/metadata/android/en-US/changelogs/3544.txt

Release v3.9.3

---

src/main/java/de/dennisguse/opentracks/settings/bluetooth/BluetoothLeSensorPreference.java
src/main/res/anim/bluetooth_searching_bigdot.xml
src/main/res/anim/bluetooth_searching_smalldot.xml
src/main/res/drawable/ic_bluetooth_searching_animated_24dp.xml

Settings: animate the Bluetooth icon.

---

src/main/java/de/dennisguse/opentracks/fragments/IntervalsRecordedFragment.java
src/main/java/de/dennisguse/opentracks/fragments/IntervalsRecordingFragment.java
src/main/java/de/dennisguse/opentracks/viewmodels/IntervalStatisticsModel.java

Fixes #406 and simplifies code.
@rgmf I have not read #407 (and should not as it is too late for reading new code ><), but it sounds like the proper fix to the trackId thing.
I will take a look tomorrow.

Refactoring.

---

src/main/java/de/dennisguse/opentracks/fragments/ExportProgressDialogFragment.java
src/main/java/de/dennisguse/opentracks/io/file/ExportFileName.java

unify creating export filename

unify export filename logic

---

src/main/java/de/dennisguse/opentracks/SearchListActivity.java
src/main/java/de/dennisguse/opentracks/TrackEditActivity.java
src/main/java/de/dennisguse/opentracks/content/SearchEngine.java
src/main/java/de/dennisguse/opentracks/content/provider/CustomSQLiteOpenHelper.java
src/main/java/de/dennisguse/opentracks/io/file/importer/AbstractFileTrackImporter.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingService.java
src/main/java/de/dennisguse/opentracks/util/IntentUtils.java

Fixed #422.
Also I've reviewed all trackId ocurrences and fixed some hidden bugs (`find ./src/main/java/de/dennisguse/opentracks -name "*.java" | xargs grep "trackId"`)

Fixes #422 and other hidden bugs around Track.Id

---

src/main/java/de/dennisguse/opentracks/services/tasks/AnnouncementPeriodicTask.java
src/main/java/de/dennisguse/opentracks/viewmodels/IntervalStatistics.java

Last interval computing fixed. That was why announcement failed.
Fixes https://github.com/OpenTracksApp/OpenTracks/issues/443

Bugfix: interval stats announced incorrectly

---

src/main/java/de/dennisguse/opentracks/io/file/importer/GpxFileTrackImporter.java

Bugfix: import gpx file added heart rate like a speed because a break was missing.

Bugfix: import gpx file added heart rate like a speed because a break was missing.

---

.idea/codeStyles/Project.xml
.idea/misc.xml

I recently upgraded Android Studio and those two .idea config files got updated.
I don't know if this is relevant for all. If not I can also ignore it locally.

idea config files with android studio upgrade

---

src/main/AndroidManifest.xml
src/main/java/de/dennisguse/opentracks/io/file/importer/ImportActivity.java

These intent filters work for me. These are like the ones you can see in OsmAnd.
Also, read this: https://stackoverflow.com/a/8599921/8727038

ImportActivity intent filters.

---

build.gradle
src/main/java/de/dennisguse/opentracks/content/sensor/SensorData.java
src/main/java/de/dennisguse/opentracks/content/sensor/SensorDataCycling.java
src/main/java/de/dennisguse/opentracks/content/sensor/SensorDataHeartRate.java
src/main/java/de/dennisguse/opentracks/content/sensor/SensorDataSet.java
src/main/java/de/dennisguse/opentracks/fragments/ChartFragment.java
src/main/java/de/dennisguse/opentracks/fragments/ChooseActivityTypeDialogFragment.java
src/main/java/de/dennisguse/opentracks/fragments/IntervalsFragment.java
src/main/java/de/dennisguse/opentracks/fragments/MarkerDetailFragment.java
src/main/java/de/dennisguse/opentracks/fragments/StatisticsRecordedFragment.java
src/main/java/de/dennisguse/opentracks/fragments/StatisticsRecordingFragment.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingService.java
src/main/java/de/dennisguse/opentracks/services/sensors/BluetoothConnectionManager.java
src/main/java/de/dennisguse/opentracks/services/sensors/BluetoothRemoteSensorManager.java
src/main/java/de/dennisguse/opentracks/util/PreferencesUtils.java

So far, we updated (using sensor name and sensor data) the UI only when a sensor actually sent us data (so we are connected to it and the sensor can send data).
However, even if not connected to a sensor, we can show it's address in the UI.

Bluetooth Sensor addresses shown while trying to connect

---

src/main/java/de/dennisguse/opentracks/TrackListActivity.java
src/main/java/de/dennisguse/opentracks/content/data/TracksColumns.java
src/main/java/de/dennisguse/opentracks/content/provider/ContentProviderUtils.java
src/main/java/de/dennisguse/opentracks/content/provider/CustomContentProvider.java

Improves performance (especially startup).
Fixes #328.

TrackListActivity now loads marker count via one query only

---

src/main/java/de/dennisguse/opentracks/fragments/IntervalsFragment.java

Run on UI thread should fix #509.

Bugfix: view changed from wrong thread. Fixes #509.

---

README_TESTED_SENSORS.md
src/androidTest/java/de/dennisguse/opentracks/content/sensor/SensorDataCyclingTest.java
src/androidTest/java/de/dennisguse/opentracks/util/BluetoothUtilsTest.java
src/main/java/de/dennisguse/opentracks/adapters/SensorsAdapter.java
src/main/java/de/dennisguse/opentracks/content/sensor/SensorDataCycling.java
src/main/java/de/dennisguse/opentracks/content/sensor/SensorDataCyclingPower.java
src/main/java/de/dennisguse/opentracks/content/sensor/SensorDataSet.java
src/main/java/de/dennisguse/opentracks/fragments/StatisticsRecordingFragment.java
src/main/java/de/dennisguse/opentracks/services/sensors/BluetoothConnectionManager.java
src/main/java/de/dennisguse/opentracks/services/sensors/BluetoothRemoteSensorManager.java
src/main/java/de/dennisguse/opentracks/settings/SettingsActivity.java
src/main/java/de/dennisguse/opentracks/settings/bluetooth/BluetoothLeCyclingPowerPreference.java
src/main/java/de/dennisguse/opentracks/util/BluetoothUtils.java
src/main/java/de/dennisguse/opentracks/util/PreferencesUtils.java
src/main/res/layout/sensor_item.xml
src/main/res/layout/statistics_recording.xml
src/main/res/values/colors.xml
src/main/res/values/do_not_translate.xml
src/main/res/values/settings.xml
src/main/res/xml/settings.xml

Add another cycling powermeter Bluetooth LE sensors.
PS: This PR is untested due to the lack of testing devices (I don't need a powermeter on my bicycle).
I am waiting for confirmation that it works (I asked somebody).

Bluetooth Sensor: add cycling powermeter.

---

src/main/java/de/dennisguse/opentracks/MarkerEditActivity.java
src/main/java/de/dennisguse/opentracks/MarkerListActivity.java
src/main/java/de/dennisguse/opentracks/fragments/DeleteMarkerDialogFragment.java
src/main/java/de/dennisguse/opentracks/io/file/importer/AbstractFileTrackImporter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/KmlFileTrackImporter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/KmzTrackImporter.java
src/main/java/de/dennisguse/opentracks/util/FileUtils.java
src/main/res/values/strings.xml

Three bugs fixed:
1. Import marker with photos didn't saved the photos.
2. Edit marker could leave not linked photos in track directory.
3. Delete marker didn't work.
#514 

Import marker photos

---

README_TESTED_SENSORS.md

- This adds Huami devices into README_TESTED_SENSORS.md
- also adds new line at the end of the file to prevent diff from complaining
Related to #445 

add Huami devices into Readme Tested Sensors

---

src/main/java/de/dennisguse/opentracks/TrackRecordedActivity.java
src/main/java/de/dennisguse/opentracks/TrackRecordingActivity.java
src/main/java/de/dennisguse/opentracks/chart/ChartView.java
src/main/res/layout-land/track_recording.xml
src/main/res/layout/track_recorded.xml
src/main/res/layout/track_recording.xml

Almost not tested.
Approach: ChartView handles all touchEvents if
* more than one pointer is down (i.e., zooming in progress), or
* the view is in zoomed mode (and the user can scroll)
otherwise the parent may react to the events.
The following case felt weird:
1. Go to "By time"
2. Zoom
3. Scroll from right to left until moving to "By distance"
4. Swipe back to "By time"
Then the ChartView is reset and thus the user needs to zoom/scroll again.
Also: The user has no indication to see when he might swipe to the next tab as s/he doesn't 
know how much is left on the x-axis.

Viewpager2 zoom

---

src/main/java/de/dennisguse/opentracks/MarkerEditActivity.java
src/main/java/de/dennisguse/opentracks/TrackListActivity.java
src/main/java/de/dennisguse/opentracks/TrackRecordedActivity.java
src/main/java/de/dennisguse/opentracks/TrackRecordingActivity.java
src/main/java/de/dennisguse/opentracks/fragments/MarkerDetailFragment.java

As of ADT 14 as well as Gradle Plugin 5.0 those are not final anymore.
Fixes #544.

Compare resourceIds via if rather than switch.

---

build.gradle
src/androidTest/java/de/dennisguse/opentracks/EspressoUITest.java
src/androidTest/java/de/dennisguse/opentracks/fragments/ChartFragmentTest.java
src/androidTest/java/de/dennisguse/opentracks/fragments/TrackStubUtils.java

Finally, some really simple, basic EspressoUI tests.
No rocket science, but better than nothing.

Espressoui#387

---

src/androidTest/java/de/dennisguse/opentracks/content/DescriptionGeneratorTest.java
src/androidTest/java/de/dennisguse/opentracks/services/sensors/ElevationSumManagerTest.java
src/androidTest/java/de/dennisguse/opentracks/util/PressureSensorUtilsTest.java
src/main/java/de/dennisguse/opentracks/adapters/IntervalStatisticsAdapter.java
src/main/java/de/dennisguse/opentracks/content/DescriptionGenerator.java
src/main/java/de/dennisguse/opentracks/content/data/TrackPoint.java
src/main/java/de/dennisguse/opentracks/content/data/TrackPointsColumns.java
src/main/java/de/dennisguse/opentracks/content/data/TracksColumns.java
src/main/java/de/dennisguse/opentracks/content/provider/CachedTrackPointsIndexes.java
src/main/java/de/dennisguse/opentracks/content/provider/ContentProviderUtils.java
src/main/java/de/dennisguse/opentracks/content/provider/CustomSQLiteOpenHelper.java
src/main/java/de/dennisguse/opentracks/fragments/StatisticsRecordedFragment.java
src/main/java/de/dennisguse/opentracks/fragments/StatisticsRecordingFragment.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/KmlTrackWriter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/KmlFileTrackImporter.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingService.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingServiceBinder.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingServiceInterface.java
src/main/java/de/dennisguse/opentracks/services/sensors/ElevationSumManager.java
src/main/java/de/dennisguse/opentracks/stats/TrackStatistics.java
src/main/java/de/dennisguse/opentracks/stats/TrackStatisticsUpdater.java
src/main/java/de/dennisguse/opentracks/util/PressureSensorUtils.java
src/main/java/de/dennisguse/opentracks/viewmodels/IntervalStatistics.java
src/main/res/drawable/ic_arrow_drop_down_24.xml
src/main/res/layout/interval_list_view.xml
src/main/res/layout/interval_stats_list_item.xml
src/main/res/layout/statistics_recorded.xml
src/main/res/layout/statistics_recording.xml
src/main/res/values/strings.xml

Several moths ago OT introduced elevation gain via barometer but loss was left. This PR adds elevation loss together gain included in intervals fragment (tab).
All tests pass and I've tested it in three real activities with good results.
#547 

Added elevation loss via barometer

---

src/main/java/de/dennisguse/opentracks/MarkerListActivity.java
src/main/java/de/dennisguse/opentracks/TrackListActivity.java
src/main/java/de/dennisguse/opentracks/adapters/ExecutorListViewService.java
src/main/java/de/dennisguse/opentracks/adapters/MarkerResourceCursorAdapter.java
src/main/java/de/dennisguse/opentracks/adapters/ScrollVisibleViews.java
src/main/java/de/dennisguse/opentracks/util/ListItemUtils.java
src/main/res/layout/list_item.xml

Photos from marker's list are loaded asynchronously and Adapter uses a cache strategy to speed up the loading. It's using 1/8 from free memory (read code).
#545 

Marker's list with photos are now loaded efficiently.

---

src/main/java/de/dennisguse/opentracks/content/TrackDataHub.java

TrackDataHub bug fixed.

---

src/main/java/de/dennisguse/opentracks/io/file/exporter/GPXTrackExporter.java

GPX export: re-implemented basic support for multiple tracks.

---

src/main/java/de/dennisguse/opentracks/fragments/StatisticsRecordingFragment.java

Recording page was just showing latitude values
- no issue
- no new deps

Fixed longitudeText in StatisticsRecordingFragment

---

src/androidTest/java/de/dennisguse/opentracks/util/StringUtilsTest.java
src/main/java/de/dennisguse/opentracks/io/file/importer/AbstractFileTrackImporter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/ImportService.java
src/main/java/de/dennisguse/opentracks/io/file/importer/ImportViewModel.java

Import: replaced SAXParserException as it only shows the message of it's cause.

---

src/main/java/de/dennisguse/opentracks/content/TrackDataHub.java
src/main/java/de/dennisguse/opentracks/content/TrackDataListener.java
src/main/java/de/dennisguse/opentracks/fragments/ChartFragment.java
src/main/java/de/dennisguse/opentracks/fragments/IntervalsFragment.java
src/main/java/de/dennisguse/opentracks/fragments/StatisticsRecordingFragment.java

Fixes #628.
The TrackDataHub not send notification if no TrackPoints were processed.

Bug: StatisticsRecordingFragment: speed and location where sometimes 0.

---

doc/data-exportimport.txt
src/androidTest/java/de/dennisguse/opentracks/io/file/importer/ExportImportTest.java
src/androidTest/java/de/dennisguse/opentracks/io/file/importer/LegacyImportTest.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/GPXTrackExporter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/AbstractFileTrackImporter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/ImportService.java
src/main/java/de/dennisguse/opentracks/io/file/importer/KmzTrackImporter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/TrackImporter.java

I just realized that GPX can contain multiple tracks.
This adds the functionality.

GPX with mutlitrack support

---

src/main/AndroidManifest.xml
src/main/java/de/dennisguse/opentracks/io/file/importer/ImportActivity.java
src/main/java/de/dennisguse/opentracks/io/file/importer/ImportViewModel.java

Fixes #559.
@vanous Could you check that this works as you expect it to work?

Import: allow import multiple select files.

---

src/main/java/de/dennisguse/opentracks/io/file/importer/ImportService.java
src/main/java/de/dennisguse/opentracks/io/file/importer/ImportServiceResultReceiver.java
src/main/java/de/dennisguse/opentracks/io/file/importer/ImportViewModel.java

Bug fixed: ImportService send a list of Track.Id

---

src/main/res/menu/track_list.xml

TrackList: show aggregated stats icon in the first slot.

---

src/androidTest/java/de/dennisguse/opentracks/util/AnnouncementUtilsTest.java
src/main/java/de/dennisguse/opentracks/util/AnnouncementUtils.java

Bugfix: announcements should consider hours when computing minutes.

---

src/main/res/values-pl/strings.xml

Pl voice notification fixes.
Fixes https://github.com/OpenTracksApp/OpenTracks/issues/595
Contribution is under the _Apache License 2.0_

Pl translation update.

---

src/main/java/de/dennisguse/opentracks/chart/ChartView.java

Fixes #42.
PS: really old bug :)

ChartView: missing (sensor) data does not draw until the end.

---

src/main/java/de/dennisguse/opentracks/util/PreferencesUtils.java

It fixes #694
@dennisguse merge it if you think it's a good solution ;)
PS/ You can reproduce the bug, can't you?

Auto export after workout bug fixed

---

README_TESTED_SENSORS.md

U: README_TESTED_SENSORS.md

---

src/main/java/de/dennisguse/opentracks/chart/ChartView.java

While working on #745 I also re-read the rendering code in ChartView.
And here is an improvement: easier to read and should be slightly faster.

ChartView: improve performance.

---

src/main/java/de/dennisguse/opentracks/services/tasks/AnnouncementPeriodicTask.java
src/main/java/de/dennisguse/opentracks/settings/SettingsActivity.java

Settings: disable voice announcement setting if not TTS available.

---

src/main/java/de/dennisguse/opentracks/ControllerFragment.java
src/main/java/de/dennisguse/opentracks/content/TrackDataHub.java
src/main/java/de/dennisguse/opentracks/content/TrackDataListener.java
src/main/java/de/dennisguse/opentracks/content/data/Track.java
src/main/java/de/dennisguse/opentracks/content/provider/ContentProviderUtils.java
src/main/java/de/dennisguse/opentracks/fragments/ChartFragment.java
src/main/java/de/dennisguse/opentracks/fragments/IntervalsFragment.java
src/main/java/de/dennisguse/opentracks/fragments/StatisticsRecordingFragment.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingService.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingServiceConnection.java
src/main/java/de/dennisguse/opentracks/services/tasks/AnnouncementPeriodicTask.java

StatisticsRecordingFragment and ControllerFragment get the data via LiveData from the TrackRecordingService (event every second).
All computation is done within the TrackRecordingService.
Replaces pull from UI layer.
Not really tested yet: only by holding the phone out of a window ;)
Cycling sensor handling must be tested in detail.
Next step: simplify TrackDataHub interface as it is only used by Charts now.

TrackRecordingService uses LiveData to transfer data.

---

src/androidTest/java/de/dennisguse/opentracks/EspressoCategoryUnitTest.java
src/main/java/de/dennisguse/opentracks/fragments/StatisticsRecordingFragment.java

The category wasn't updating properly (see code).
I've added Espresso test so this issue shouldn't reproduce anymore.

Bugfix: category change didn't update speed/pace correctly.

---

src/main/java/de/dennisguse/opentracks/content/TrackDataHub.java

TrackDataHub: prevent crash due to race condition.

---

README_TESTED_SENSORS.md
src/androidTest/java/de/dennisguse/opentracks/util/UintUtilsTest.java
src/main/java/de/dennisguse/opentracks/content/data/TrackPoint.java
src/main/java/de/dennisguse/opentracks/content/sensor/SensorDataCycling.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingService.java
src/main/java/de/dennisguse/opentracks/stats/DoubleRingBuffer.java
src/main/java/de/dennisguse/opentracks/stats/TrackStatisticsUpdater.java
src/main/java/de/dennisguse/opentracks/util/StringUtils.java
src/main/java/de/dennisguse/opentracks/util/UintUtils.java

While refactoring StatisticsRecordingFragment, the UI update was not implemented correctly, when using wheel rotation sensor.
PS: There also seems to be an issue computing the speed.
Distance seems fine. Not sure yet.
Fixes #810.

Fixed: using a wheel rotation sensor for speed and distance did not show on UI

---

src/androidTest/java/de/dennisguse/opentracks/EspressoCategoryUnitTest.java
src/androidTest/java/de/dennisguse/opentracks/PreferenceMetricUnitRule.java
src/main/java/de/dennisguse/opentracks/Startup.java
src/main/java/de/dennisguse/opentracks/util/PreferencesUtils.java

i am running the tests only in emulators as some of them delete data or modify preferences.
And my emulator starts with Locale.US, but this tests assumes that we are a non-US device.
So, we set it ;)

EspressoCategoryUnitTest needs to set metricUnits.

---

src/main/java/de/dennisguse/opentracks/services/tasks/AnnouncementPeriodicTask.java
src/main/java/de/dennisguse/opentracks/settings/SettingsActivity.java
src/main/java/de/dennisguse/opentracks/util/PreferencesUtils.java
src/main/res/values/settings.xml
src/main/res/values/strings.xml
src/main/res/xml/settings.xml

Voice announcement: make rate configurable.

---

src/main/AndroidManifest.xml
src/main/java/de/dennisguse/opentracks/TrackListActivity.java

Untested changes for Android12.

Android 12 updates (mainly permissions)

---

src/main/res/values-zh/strings.xml

Translation: update Chinese translation

---

src/main/java/de/dennisguse/opentracks/services/TrackRecordingServiceNotificationManager.java

TrackRecordingService: notification should not vibrate.

Xioami remove continuous vibration

---

README.md
README_TESTED_SENSORS.md
src/androidTest/java/de/dennisguse/opentracks/util/BluetoothUtilsTest.java
src/main/java/de/dennisguse/opentracks/content/data/Distance.java
src/main/java/de/dennisguse/opentracks/content/sensor/SensorDataRunning.java
src/main/java/de/dennisguse/opentracks/content/sensor/SensorDataSet.java
src/main/java/de/dennisguse/opentracks/services/sensors/BluetoothConnectionManager.java
src/main/java/de/dennisguse/opentracks/services/sensors/BluetoothRemoteSensorManager.java
src/main/java/de/dennisguse/opentracks/settings/SettingsActivity.java
src/main/java/de/dennisguse/opentracks/settings/bluetooth/BluetoothLeRunningSpeedAndCadencePreference.java
src/main/java/de/dennisguse/opentracks/util/BluetoothUtils.java
src/main/java/de/dennisguse/opentracks/util/PreferencesUtils.java
src/main/java/de/dennisguse/opentracks/util/UnitConversions.java
src/main/res/values/settings.xml
src/main/res/values/strings.xml
src/main/res/xml/settings.xml

Fixes #891.
Not yet properly tested (just implemented by specification).
Will be `forced pushed`.

Sensor: adding Running Speed and Cadence.

---

src/main/java/de/dennisguse/opentracks/adapters/StatsAdapter.java
src/main/java/de/dennisguse/opentracks/content/data/Layout.java
src/main/java/de/dennisguse/opentracks/util/StringUtils.java
src/main/java/de/dennisguse/opentracks/viewmodels/StatsData.java
src/main/java/de/dennisguse/opentracks/viewmodels/StatsDataBuilder.java

My suggestions for StatsBuilder;
Please squash this when accepted - too messy as a commit ;)

Cleanup: some changes

---

src/main/java/de/dennisguse/opentracks/io/file/exporter/ExportActivity.java
src/main/res/layout/export_activity.xml

I've fixed #902 bug using the following article:
https://chetangupta.net/viewbinding/#includeMerge
#902 

Bugfix: generated fields for include and merge tags.

---

src/main/java/de/dennisguse/opentracks/content/data/TrackPoint.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingManager.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingService.java
src/main/java/de/dennisguse/opentracks/services/handlers/TrackPointCreator.java

Fixes #901.
All this recording code needs still a lot of love.

Bugfix: reset TrackRecordingManager properly.

---

.github/workflows/build_nightly.yml
build.gradle

This PR adds a Github Action task that builds a signed APK and attaches it as an artifact to the Github Action result.

CI: build nightly on push.

---

src/main/java/de/dennisguse/opentracks/adapters/IntervalStatisticsAdapter.java
src/main/java/de/dennisguse/opentracks/fragments/StatisticsRecordedFragment.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/SharePictureTrackExporter.java
src/main/java/de/dennisguse/opentracks/util/StringUtils.java
src/main/java/de/dennisguse/opentracks/viewmodels/StatisticDataBuilder.java

Altitude, gain and loss are showed like floats with 1 decimal.
I think, gain and loss should be integers because they always are X.0
In this PR are the changes for this.

[PROPOSAL] Gain and loss are integers

---

src/main/AndroidManifest.xml
src/main/java/de/dennisguse/opentracks/settings/bluetooth/BluetoothLeSensorPreference.java
src/main/res/values-de/strings.xml
src/main/res/values/strings.xml

Ask for permission before using Bluetooth.
The Toast telling the user to manually go to settings should be replaced by a proper dialog at some point. I just didn't have the time for now :sweat_smile: 
#942 

Ask for permission before using Bluetooth

---

README_TESTED_SENSORS.md

Added information about smartphones with barometric sensor to README_TESTED_SENSORS.md

Added phones with barometric sensor information.

---

src/nightly/res/values/strings.xml

Nightly build: app name with suffix.

---

src/main/java/de/dennisguse/opentracks/content/data/Speed.java
src/main/java/de/dennisguse/opentracks/settings/GpsSettingsFragment.java
src/main/java/de/dennisguse/opentracks/settings/PreferencesUtils.java
src/main/res/values/settings.xml
src/main/res/values/strings.xml
src/main/res/xml/settings_gps.xml

... I prepared this some weeks ago, but it needs to be rebased.

Setting for idle speed

---

README.md

I had some time and published OpenTracks to the Amazon App Store as well.

README: add link to Amazon App Store

---

src/androidTest/java/de/dennisguse/opentracks/services/TrackRecordingServiceTestLocation.java
src/main/java/de/dennisguse/opentracks/content/data/TrackPoint.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingManager.java

Proposed solution to #1007 
https://github.com/OpenTracksApp/OpenTracks/issues/1007#issue-1041879140

Proposed solution for recording points that do not meet filter conditions

---

src/main/java/de/dennisguse/opentracks/settings/SettingsActivity.java

This should fixes #1022 
#1022

Illegal state exception crashed fixed

---

src/androidTest/java/de/dennisguse/opentracks/io/file/importer/ExportImportTest.java
src/androidTest/java/de/dennisguse/opentracks/io/file/importer/TrackPointAssert.java
src/androidTest/java/de/dennisguse/opentracks/services/TrackRecordingServiceTest.java
src/androidTest/java/de/dennisguse/opentracks/services/TrackRecordingServiceTestLocation.java
src/androidTest/java/de/dennisguse/opentracks/services/TrackRecordingServiceTestStatistics.java
src/androidTest/java/de/dennisguse/opentracks/stats/TrackStatisticsUpdaterTest.java
src/main/java/de/dennisguse/opentracks/content/data/TrackPoint.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingManager.java
src/main/java/de/dennisguse/opentracks/stats/TrackStatisticsUpdater.java

Reverting changes to fix moving time issue.

Moving time#1046

---

README_TESTED_SENSORS.md
src/main/java/de/dennisguse/opentracks/services/sensors/BluetoothConnectionManager.java

Fixes #1050 .
Will be merged ~before~ after v3.23.0.

Wahoo#1050

---

src/androidTest/java/de/dennisguse/opentracks/util/StringUtilsTest.java

Trying to fix strange fails in this test.

StringUtilsTest.testFormatDateTime

---

src/main/java/de/dennisguse/opentracks/chart/ChartView.java

Fixes #1086.
@vsevjednom-cz Does this fix the issue?
Don't know exactly how I broke it - too late for an investigation :)

Bugfix: ChartView needs data.

---

src/androidTest/java/de/dennisguse/opentracks/content/data/TestDataUtil.java
src/main/java/de/dennisguse/opentracks/data/ContentProviderUtils.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/KMLTrackExporter.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/KmzTrackExporter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/TrackImporter.java
src/main/java/de/dennisguse/opentracks/services/announcement/VoiceAnnouncement.java
src/main/java/de/dennisguse/opentracks/ui/markers/MarkerEditActivity.java
src/main/java/de/dennisguse/opentracks/ui/markers/MarkerEditViewModel.java
src/main/java/de/dennisguse/opentracks/ui/markers/MarkerUtils.java
src/main/java/de/dennisguse/opentracks/util/FileUtils.java
src/main/java/de/dennisguse/opentracks/util/IntentUtils.java

Cleanup marker edit

---

src/androidTest/java/de/dennisguse/opentracks/services/TrackRecordingServiceTestUtils.java
src/main/java/de/dennisguse/opentracks/TrackRecordedActivity.java
src/main/java/de/dennisguse/opentracks/TrackRecordingActivity.java
src/main/java/de/dennisguse/opentracks/data/TrackDataHub.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingManager.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingService.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingServiceNotificationManager.java
src/main/java/de/dennisguse/opentracks/services/announcement/VoiceAnnouncementManager.java
src/main/java/de/dennisguse/opentracks/services/handlers/GPSHandler.java
src/main/java/de/dennisguse/opentracks/services/handlers/TrackPointCreator.java

Just some cleanups while working on #1052.

Service#1052

---

src/androidTest/java/de/dennisguse/opentracks/io/file/importer/ExportImportTest.java
src/androidTest/java/de/dennisguse/opentracks/io/file/importer/GPXImportTest.java
src/androidTest/java/de/dennisguse/opentracks/io/file/importer/KMLImportTest.java
src/androidTest/java/de/dennisguse/opentracks/services/announcement/VoiceAnnouncementUtilsTest.java
src/androidTest/java/de/dennisguse/opentracks/stats/TrackStatisticsUpdaterTest.java
src/androidTest/java/de/dennisguse/opentracks/ui/intervals/IntervalStatisticsTest.java
src/main/java/de/dennisguse/opentracks/TrackRecordingActivity.java
src/main/java/de/dennisguse/opentracks/data/ShareContentProvider.java
src/main/java/de/dennisguse/opentracks/io/file/importer/ImportService.java
src/main/java/de/dennisguse/opentracks/io/file/importer/TrackImporter.java
src/main/java/de/dennisguse/opentracks/services/announcement/VoiceAnnouncement.java
src/main/java/de/dennisguse/opentracks/settings/ImportExportSettingsFragment.java
src/main/java/de/dennisguse/opentracks/ui/intervals/IntervalStatistics.java
src/main/java/de/dennisguse/opentracks/ui/intervals/IntervalStatisticsModel.java

Some cleanups.

---

src/androidTest/java/de/dennisguse/opentracks/services/TrackRecordingServiceTestStateMachine.java
src/androidTest/java/de/dennisguse/opentracks/services/announcement/VoiceAnnouncementManagerTest.java
src/androidTest/java/de/dennisguse/opentracks/viewmodels/StatisticDataBuilderTest.java
src/main/java/de/dennisguse/opentracks/ControllerFragment.java
src/main/java/de/dennisguse/opentracks/TrackListActivity.java
src/main/java/de/dennisguse/opentracks/TrackRecordedActivity.java
src/main/java/de/dennisguse/opentracks/TrackRecordingActivity.java
src/main/java/de/dennisguse/opentracks/data/TrackDataHub.java
src/main/java/de/dennisguse/opentracks/fragments/StatisticsRecordingFragment.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/ExportActivity.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/ExportServiceResultReceiver.java
src/main/java/de/dennisguse/opentracks/services/RecordingData.java
src/main/java/de/dennisguse/opentracks/services/RecordingStatus.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingManager.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingService.java
src/main/java/de/dennisguse/opentracks/services/announcement/VoiceAnnouncement.java
src/main/java/de/dennisguse/opentracks/services/announcement/VoiceAnnouncementManager.java
src/main/java/de/dennisguse/opentracks/services/handlers/TrackPointCreator.java
src/main/java/de/dennisguse/opentracks/settings/MainSettingsFragment.java
src/main/java/de/dennisguse/opentracks/ui/markers/MarkerListActivity.java
src/main/java/de/dennisguse/opentracks/util/ExportUtils.java
src/main/java/de/dennisguse/opentracks/viewmodels/StatisticDataBuilder.java
src/main/java/de/dennisguse/opentracks/viewmodels/StatisticsDataModel.java

... not yet sure how the final result will look like :sunglasses:

Refactoring TrackRecordingService for #1052

---

src/main/java/de/dennisguse/opentracks/TrackListActivity.java
src/main/java/de/dennisguse/opentracks/TrackRecordingActivity.java
src/main/java/de/dennisguse/opentracks/services/handlers/GPSHandler.java
src/main/java/de/dennisguse/opentracks/util/PermissionUtils.java

... as we almost have a snackbar: we can make GPS optional :)

Gps permission#1061

---

src/main/java/de/dennisguse/opentracks/services/TrackRecordingManager.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingService.java
src/main/java/de/dennisguse/opentracks/services/handlers/GPSHandler.java
src/main/java/de/dennisguse/opentracks/services/handlers/TrackPointCreator.java

Fixes #1117.
Should only fix the problem for using the GPS.
BLE sensors might still be affected if they were - I had no time to check it.

Bugfix: speed showed sometimes 0.0 in UI.

---

src/main/java/de/dennisguse/opentracks/services/TrackRecordingService.java

Accidentally introduced in 78519883c07eeecff930e747433c868e3f631f02.
I was investigating an issue and for this decreased the UI update interval to 100ms, but merged it into main.
This PR moves it back to 1s.

UI: only update once every second.

---

src/main/res/layout/stats_clock_item.xml

UI: while recording clock shows seconds.

---

src/main/java/de/dennisguse/opentracks/io/file/exporter/GPXTrackExporter.java

To each trackpiont written to the GPX file.
Fixes: #1160

Use Cluetrust GPX extension to add total distance

---

src/main/java/de/dennisguse/opentracks/services/TrackRecordingService.java

Fixes #1189.
This should fix the issue, but I am not sure how to reproduce this race condition.

Bugfix: onDestroy() first shutdown sensors.

---

src/androidTest/java/de/dennisguse/opentracks/io/file/importer/ExportImportTest.java
src/androidTest/java/de/dennisguse/opentracks/services/handlers/GPSHandlerTest.java
src/main/java/de/dennisguse/opentracks/services/handlers/GPSHandler.java
src/main/java/de/dennisguse/opentracks/services/handlers/TrackPointCreator.java
src/main/java/de/dennisguse/opentracks/util/LocationUtils.java

See https://github.com/OpenTracksApp/OpenTracks/issues/1151#issuecomment-1086693660
Solution: properly synchronize the two methods.
TODO:

Bugfix: race condition when using multiple sensors

---

doc/opentracks-schema-1.0.xsd
src/androidTest/java/de/dennisguse/opentracks/io/file/importer/ExportImportTest.java
src/androidTest/java/de/dennisguse/opentracks/io/file/importer/TrackPointAssert.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/GPXTrackExporter.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/KMLTrackExporter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/GpxTrackImporter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/KmlTrackImporter.java

Follow-up to #1182.
@brianjmurrell Does this work for you?

Import/Export GPS accuracy ot GPX/KML

---

.github/workflows/test.yml
src/androidTest/java/de/dennisguse/opentracks/TimezoneRule.java
src/androidTest/java/de/dennisguse/opentracks/io/file/importer/ExportImportTest.java
src/androidTest/res/raw/csv_export.csv
src/main/java/de/dennisguse/opentracks/data/ShareContentProvider.java
src/main/java/de/dennisguse/opentracks/io/file/TrackFileFormat.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/CSVTrackExporter.java
src/main/java/de/dennisguse/opentracks/settings/ImportExportSettingsFragment.java

Fixes #999.
Really not fancy.
@brianjmurrell does this work for you?

Add CSV as export format (TrackPoints only).

---

src/main/java/de/dennisguse/opentracks/ui/intervals/IntervalsFragment.java

Intervals dropdown shows wrong unit

---

src/androidTest/java/de/dennisguse/opentracks/data/ShareContentProviderTest.java
src/main/java/de/dennisguse/opentracks/data/ShareContentProvider.java

Introduced in 0d3cf4ce0d56ec756f1a3b1ff19cbef6cf95275d.
(If available): The link to the issue that this pull …

Bugfix: sharing track added file suffix twice.

---

src/main/java/de/dennisguse/opentracks/publicapi/StopRecording.java

Fixes #1225.
Don't know if this is the best implementation.

Public API: respect post-workout export.

---

src/androidTest/java/de/dennisguse/opentracks/io/file/TrackFilenameGeneratorTest.java
src/main/java/de/dennisguse/opentracks/io/file/TrackFilenameGenerator.java
src/main/res/values/settings.xml

Refine filename formats.
Got the request by email.

Export: filename template now distinguishes between {date} and {time}.

---

src/androidTest/java/de/dennisguse/opentracks/EspressoUITest.java
src/main/java/de/dennisguse/opentracks/TrackStoppedActivity.java

Introduced in 9d64989ef1d64b7d9146f3643ab8ceb39a2e9c58
I guess that would make us ready for another release.
PS/ v3.28.0 was not build by F-Droid as I tagged the wrong commit.
So, only nightly/PlayStore users were affected by the preference issues/ crashes.

Bugfix: resume functionality was not starting recording.

---

src/androidTest/java/de/dennisguse/opentracks/io/file/importer/GPXTrackImporterTest.java
src/androidTest/java/de/dennisguse/opentracks/io/file/importer/KMLTrackImporterTest.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/KMLTrackExporter.java

Stuff from #1217 that were not upgrading to KML2.3

KML changes (without KML2.3)

---

src/androidTest/java/de/dennisguse/opentracks/EspressoDeleteTrackTest.java
src/androidTest/java/de/dennisguse/opentracks/EspressoUITest.java

Fix EspressoDeleteTrackTest.

---

src/main/java/de/dennisguse/opentracks/TrackStoppedActivity.java
src/main/res/layout/track_stopped.xml

Fields and data summary are inside an ScrollView and buttons are always visible.
#1257

Bugfixes: TrackStoppedActivity on smaller devices. Fixes #1257.

---

src/main/java/de/dennisguse/opentracks/TrackListActivity.java
src/main/java/de/dennisguse/opentracks/TrackRecordingActivity.java

Introduced in 9d64989ef1d64b7d9146f3643ab8ceb39a2e9c58
Somehow missed this change for the 4.0.0 release...

Bugfix: request permissions in TrackListActivity.

---

src/main/res/drawable/ic_button_done.xml
src/main/res/drawable/ic_button_resume.xml

Added colors in XML resume and finish buttons.
#1260 

Bugfixes: buttons colors were handcoded

---

src/main/java/de/dennisguse/opentracks/TrackRecordingActivity.java

We could also go for the display cutout, but my phone doesn't support it.
https://developer.android.com/reference/android/view/WindowManager.LayoutParams#LAYOUT_IN_DISPLAY_CUTOUT_MODE_ALWAYS

Fullscreen: now more fullscreen.

---

src/androidTest/java/de/dennisguse/opentracks/services/announcement/VoiceAnnouncementUtilsTest.java
src/main/java/de/dennisguse/opentracks/services/announcement/VoiceAnnouncement.java
src/main/java/de/dennisguse/opentracks/services/announcement/VoiceAnnouncementUtils.java
src/main/java/de/dennisguse/opentracks/settings/PreferencesUtils.java
src/main/res/values-b+es+419/strings.xml
src/main/res/values-cs/strings.xml
src/main/res/values-es/strings.xml
src/main/res/values-fr/strings.xml
src/main/res/values-gl/strings.xml
src/main/res/values-nb/strings.xml
src/main/res/values-nl/strings.xml
src/main/res/values-pt-rBR/strings.xml
src/main/res/values-ru/strings.xml
src/main/res/values-sl/strings.xml
src/main/res/values-tr/strings.xml
src/main/res/values-vi/strings.xml
src/main/res/values/settings.xml
src/main/res/values/strings.xml
src/main/res/xml/settings_announcements.xml

Ported @spacecowboy voice config commit.
Somehow it got lost.

Added settings for what to announce

---

src/androidTest/java/de/dennisguse/opentracks/data/models/DistanceFormatterTest.java
src/androidTest/java/de/dennisguse/opentracks/data/models/SpeedFormatterTest.java
src/main/java/de/dennisguse/opentracks/chart/ChartValueSeries.java
src/main/java/de/dennisguse/opentracks/chart/ChartView.java
src/main/java/de/dennisguse/opentracks/data/models/Distance.java
src/main/java/de/dennisguse/opentracks/data/models/DistanceFormatter.java
src/main/java/de/dennisguse/opentracks/data/models/Speed.java
src/main/java/de/dennisguse/opentracks/data/models/SpeedFormatter.java
src/main/java/de/dennisguse/opentracks/data/models/UnitConversions.java
src/main/java/de/dennisguse/opentracks/services/announcement/VoiceAnnouncementUtils.java
src/main/java/de/dennisguse/opentracks/settings/DefaultsSettingsFragment.java
src/main/java/de/dennisguse/opentracks/settings/PreferencesUtils.java
src/main/java/de/dennisguse/opentracks/settings/UnitSystem.java
src/main/res/values/settings.xml
src/main/res/values/strings.xml

Adds nautical unit system: nautical miles with feet.
Useful for nautical and aerial tracks.

Nautical#1280

---

README.md

Replace Start with Stop

---

src/androidTest/java/de/dennisguse/opentracks/util/StringUtilsTest.java

Cleanup tests for StringUtils.parseTime().

---

README.md
src/main/java/de/dennisguse/opentracks/publicapi/StartRecording.java
src/main/java/de/dennisguse/opentracks/util/IntentDashboardUtils.java

@sgofferj does this work for you?
Fixes #1282.

Public API: allow setting track properties (name, category, description) on StartRecording)

---

src/main/java/de/dennisguse/opentracks/sensors/AltitudeSumManager.java
src/main/java/de/dennisguse/opentracks/services/handlers/TrackPointCreator.java

We don't need to process the pressure sensor as fast we were doing it.
5s should even be way to fast for most cases like hiking and cycling.
@rgmf could you test in some mountainish areas?

Gain loss delay

---

src/main/java/de/dennisguse/opentracks/ui/intervals/IntervalStatistics.java

Fixes #1320.
Does this make sense?

Cleanup: adjusted Interval uses constructor.

---

src/main/java/de/dennisguse/opentracks/ui/markers/MarkerEditActivity.java

This PR fixes #1321 for me.
#1321

Bugfixed: adding a mark with a photo after rotating in camera resulted in a crash.

---

src/main/java/de/dennisguse/opentracks/services/announcement/VoiceAnnouncement.java

.... just for CI; nothing fancy.

Deprecation warning

---

src/main/java/de/dennisguse/opentracks/publicapi/AbstractAPIActivity.java
src/main/java/de/dennisguse/opentracks/publicapi/StartRecording.java

Bugfix: Public API stop does not start service in foreground.

---

src/androidTest/java/de/dennisguse/opentracks/share/DescriptionGeneratorTest.java
src/main/java/de/dennisguse/opentracks/fragments/StatisticsRecordedFragment.java
src/main/java/de/dennisguse/opentracks/share/DescriptionGenerator.java
src/main/java/de/dennisguse/opentracks/ui/util/ListItemUtils.java
src/main/java/de/dennisguse/opentracks/util/StringUtils.java

UI: show timezone if different than local.

---

README.md
src/main/java/de/dennisguse/opentracks/publicapi/StartRecording.java
src/main/java/de/dennisguse/opentracks/util/TrackUtils.java

PublicAPI: support setting the icon.

---

src/main/AndroidManifest.xml
src/main/java/de/dennisguse/opentracks/AboutActivity.java
src/main/java/de/dennisguse/opentracks/TrackListActivity.java
src/main/java/de/dennisguse/opentracks/introduction/IntroductionActivity.java
src/main/java/de/dennisguse/opentracks/introduction/OSMDashboardFragment.java
src/main/java/de/dennisguse/opentracks/introduction/WelcomeFragment.java
src/main/java/de/dennisguse/opentracks/settings/PreferencesUtils.java
src/main/res/drawable/osmdashboard_ic_logo_color_24dp.xml
src/main/res/layout/introduction.xml
src/main/res/layout/osm_dashboard.xml
src/main/res/layout/welcome.xml
src/main/res/values/settings.xml
src/main/res/values/strings.xml

Fixes #1316.
Not really beautiful, but it is a start ...
... and the first in-app advertisement :sunglasses: 
Intro screen will only be shown once; need to reset preferences to show it again.

Implement introduction screen.

---

build.gradle

Introduced in 594f69320a57c102db8361ac3a596a7d825f5253

Unpin indirect dependency versions again (upstream fixed it).

---

src/main/java/de/dennisguse/opentracks/services/TrackRecordingService.java

Bugfix: prevent crash while stopping recording (race condition).

---

README.md

Fixes the structure of a sentence.

Fix Sentence

---

src/main/res/values-zh-rTW/strings.xml

Updated traditional Chinese translation

---

README.md

README: add dedicated link ot weblate.

---

src/androidTest/java/de/dennisguse/opentracks/io/file/importer/ExportImportTest.java
src/androidTest/java/de/dennisguse/opentracks/io/file/importer/GPXTrackImporterTest.java
src/main/AndroidManifest.xml
src/main/java/de/dennisguse/opentracks/data/ShareContentProvider.java
src/main/java/de/dennisguse/opentracks/io/file/TrackFilenameGenerator.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/CSVTrackExporter.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/ExportActivity.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/ExportService.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/ExportServiceResultReceiver.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/ExportTask.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/GPXTrackExporter.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/KMLTrackExporter.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/KmzTrackExporter.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/TrackExporter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/DirectoryChooserActivity.java
src/main/java/de/dennisguse/opentracks/util/ExportUtils.java
src/main/res/values/strings.xml
src/main/res/xml/settings_import_export.xml

I created a rough draft to export all tracks into one file.
TODO:
@rgmf I was looking through the ExportService (and the communcation with it) and I am not sure how to do this.
Any suggestions?

Rough draft for export all tracks into one file

---

src/main/java/de/dennisguse/opentracks/ui/markers/MarkerEditActivity.java

Fixes #1620.
We should use the photo picker (especially from Android 13 onwards).
https://developer.android.com/training/data-storage/shared/photopicker

Bugfix: Android 13 couldn't open Gallery.

---

src/main/java/de/dennisguse/opentracks/ui/aggregatedStatistics/AggregatedStatisticsAdapter.java

Fix aggregated stats don't show imperial units for avg pace

---

src/main/java/de/dennisguse/opentracks/fragments/StatisticsRecordedFragment.java
src/main/res/layout/statistics_recorded.xml
src/main/res/values/strings.xml

Closes: #1426
This is an alternative version of #1646, which doesn't use the RecyclerView.

Reimplement sensor statistics in UI

---

src/main/AndroidManifest.xml
src/main/java/de/dennisguse/opentracks/services/TrackRecordingService.java
src/main/java/de/dennisguse/opentracks/services/handlers/AltitudeCorrectionManager.java

Android14: crash due to missing announcement of ForegroundServiceType.

---

src/main/java/de/dennisguse/opentracks/ui/aggregatedStatistics/AggregatedStatisticsActivity.java
src/main/java/de/dennisguse/opentracks/ui/aggregatedStatistics/AggregatedStatisticsAdapter.java
src/main/res/layout/aggregated_stats.xml
src/main/res/layout/aggregated_stats_list_item.xml

Part of: #1613
Arguably, since there aren't too many `ActivityType`s a person usually tracks, this change doesn't improve performance much.

AggregatedStatisticsActivity: Convert ListView to RecyclerView

---

src/androidTest/java/de/dennisguse/opentracks/services/TrackRecordingServiceRecordingTest.java
src/androidTest/res/raw/csv_export.csv
src/main/java/de/dennisguse/opentracks/data/CustomSQLiteOpenHelper.java
src/main/java/de/dennisguse/opentracks/data/models/TrackPoint.java
src/main/java/de/dennisguse/opentracks/data/tables/TrackPointsColumns.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/CSVTrackExporter.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/GPXTrackExporter.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/KMLTrackExporter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/KmlTrackImporter.java
src/main/java/de/dennisguse/opentracks/services/handlers/TrackPointCreator.java

Idle preparation#1187

---

build.gradle
src/androidTest/java/de/dennisguse/opentracks/content/data/TestDataUtil.java
src/androidTest/java/de/dennisguse/opentracks/data/CustomContentProviderUtilsTest.java
src/androidTest/java/de/dennisguse/opentracks/util/TrackNameUtilsTest.java
src/main/java/de/dennisguse/opentracks/TrackEditActivity.java
src/main/java/de/dennisguse/opentracks/data/ContentProviderUtils.java
src/main/java/de/dennisguse/opentracks/data/CustomSQLiteOpenHelper.java
src/main/java/de/dennisguse/opentracks/data/ShareContentProvider.java
src/main/java/de/dennisguse/opentracks/data/TrackDataHub.java
src/main/java/de/dennisguse/opentracks/data/TrackSelection.java
src/main/java/de/dennisguse/opentracks/data/models/Track.java
src/main/java/de/dennisguse/opentracks/data/models/TrackPoint.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingManager.java
src/main/java/de/dennisguse/opentracks/share/ShareUtils.java
src/main/java/de/dennisguse/opentracks/ui/markers/MarkerListActivity.java
src/main/java/de/dennisguse/opentracks/util/FileUtils.java
src/main/java/de/dennisguse/opentracks/util/TrackNameUtils.java

Part of #1526.
Blocked by: https://issuetracker.google.com/issues/289237734
Requires an updated version of R8 (Version 8.1.58 or later) that is not bundled into Android Gradle Plugin `8.1.0` or `8.1.1`.
8.2.0 already works but is in alpha.
After this upgrade test should be running again.

Java Record for Track.Id and TrackPoint.Id.

---

src/main/java/de/dennisguse/opentracks/io/file/exporter/ExportActivity.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/ExportService.java
src/main/java/de/dennisguse/opentracks/settings/SettingsActivity.java
src/main/java/de/dennisguse/opentracks/util/ExportUtils.java

Let's show the exact error message of the automatic post workout export to the user, so we can analyze what is happening in #1669 .
For the manual export, I'm just logging the errors at the moment. But we could also add it to the `trackErrors` List.

show postworkout error messages, #1669

---

README.md

Add SportsTracker to file format compatibility table.
As discussed [here](https://github.com/OpenTracksApp/OpenTracks/discussions/1667)
N/A

Add SportsTracker to README.md

---

src/main/java/de/dennisguse/opentracks/data/ContentProviderUtils.java
src/main/java/de/dennisguse/opentracks/data/CustomContentProvider.java
src/main/java/de/dennisguse/opentracks/data/tables/TrackPointsColumns.java
src/main/java/de/dennisguse/opentracks/fragments/StatisticsRecordedFragment.java
src/main/java/de/dennisguse/opentracks/stats/SensorStatistics.java
src/main/res/layout/statistics_recorded.xml
src/main/res/values/strings.xml

Add max power stats

---

src/main/java/de/dennisguse/opentracks/ui/TrackListAdapter.java
src/main/java/de/dennisguse/opentracks/ui/markers/MarkerListAdapter.java

I also forgot one line in TrackListAdapter

Marker List: Fix crashes in selection mode

---

build.gradle
src/main/java/de/dennisguse/opentracks/Startup.java
src/main/java/de/dennisguse/opentracks/settings/PreferencesUtils.java
src/main/java/de/dennisguse/opentracks/settings/UserInterfaceSettingsFragment.java
src/main/res/values/settings.xml
src/main/res/values/strings.xml
src/main/res/xml/settings_announcements.xml
src/main/res/xml/settings_user_interface.xml

Finally, we got support for MaterialDesign3 DynamicColors.
Android 12+ only.
:shrug:

Android12+: use user-defined DynamicColors.

---

src/main/res/values/do_not_translate.xml

Add `template` parameter to report_issue_link, see #1738

add template parameter to report_issue_link

---

src/main/res/xml/settings_announcements.xml

As discussed in #1748 this is an attempt to fix that issue.

Fix idle announcement settings

---

build.gradle
src/main/java/de/dennisguse/opentracks/TrackEditActivity.java
src/main/java/de/dennisguse/opentracks/TrackListActivity.java
src/main/java/de/dennisguse/opentracks/TrackRecordedActivity.java
src/main/java/de/dennisguse/opentracks/TrackRecordingActivity.java
src/main/java/de/dennisguse/opentracks/TrackStoppedActivity.java
src/main/java/de/dennisguse/opentracks/fragments/StatisticsRecordingFragment.java
src/main/java/de/dennisguse/opentracks/publicapi/AbstractAPIActivity.java
src/main/java/de/dennisguse/opentracks/publicapi/StartRecording.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingService.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingServiceConnection.java
src/main/java/de/dennisguse/opentracks/ui/markers/MarkerEditViewModel.java
src/main/java/de/dennisguse/opentracks/ui/markers/MarkerListActivity.java

While working on #1708 (PR #1793), I found that the TrackRecordingServiceConnection was rather complicated to use.
Now it is simpler again :D

Refactoring TrackRecordingService

---

src/androidTest/java/de/dennisguse/opentracks/io/file/importer/ExportImportTest.java
src/androidTest/java/de/dennisguse/opentracks/sensors/sensorData/AggregatorBarometerTest.java
src/main/java/de/dennisguse/opentracks/sensors/BluetoothConnectionManager.java
src/main/java/de/dennisguse/opentracks/sensors/BluetoothHandlerBarometricPressure.java
src/main/java/de/dennisguse/opentracks/sensors/BluetoothRemoteSensorManager.java
src/main/java/de/dennisguse/opentracks/sensors/GainManager.java
src/main/java/de/dennisguse/opentracks/sensors/SensorType.java
src/main/java/de/dennisguse/opentracks/sensors/driver/BarometerInternal.java
src/main/java/de/dennisguse/opentracks/sensors/driver/Driver.java
src/main/java/de/dennisguse/opentracks/sensors/sensorData/AggregatorBarometer.java
src/main/java/de/dennisguse/opentracks/sensors/sensorData/SensorDataSet.java
src/main/java/de/dennisguse/opentracks/settings/PreferencesUtils.java
src/main/java/de/dennisguse/opentracks/settings/bluetooth/BluetoothLeAdapter.java
src/main/java/de/dennisguse/opentracks/settings/bluetooth/BluetoothLeCyclingPowerPreference.java
src/main/java/de/dennisguse/opentracks/settings/bluetooth/BluetoothLeCyclingSpeedPreference.java
src/main/java/de/dennisguse/opentracks/settings/bluetooth/BluetoothLePressurePreference.java
src/main/java/de/dennisguse/opentracks/settings/bluetooth/BluetoothLeRunningSpeedAndCadencePreference.java
src/main/java/de/dennisguse/opentracks/settings/bluetooth/BluetoothLeSensorPreference.java
src/main/res/values/settings.xml
src/main/res/values/strings.xml
src/main/res/xml/settings_sensors.xml

Getting closer to getting  BLE Barometer

---

src/main/java/de/dennisguse/opentracks/sensors/BluetoothHandlerBarometricPressure.java
src/main/java/de/dennisguse/opentracks/sensors/sensorData/AggregatorCyclingPower.java
src/main/java/de/dennisguse/opentracks/sensors/sensorData/SensorDataSet.java

Bugfix: process cycling power sensor data correctly.

---

src/main/java/de/dennisguse/opentracks/sensors/BluetoothConnectionManager.java
src/main/java/de/dennisguse/opentracks/sensors/GainManager.java
src/main/java/de/dennisguse/opentracks/sensors/SensorManager.java
src/main/java/de/dennisguse/opentracks/services/handlers/AltitudeCorrectionManager.java

Bugfix: a BLE sensor disconnect should only replace the aggregator.

---

src/androidTest/java/de/dennisguse/opentracks/sensors/BluetoothHandlerBarometricPressureTest.java
src/main/java/de/dennisguse/opentracks/data/models/AtmosphericPressure.java

Fixes #1424.
@vlszabolcs happy testing :D

Bugfix: BLE pressure is in PA.

---

src/main/java/de/dennisguse/opentracks/chart/ChartView.java

Increases horizontal chart area by putting x-axis label below the axis and a bit to the left.
#1820

add chart area space by putting x-axis label below the axis

---

src/main/java/de/dennisguse/opentracks/services/TrackRecordingServiceConnection.java
src/main/java/de/dennisguse/opentracks/ui/markers/MarkerEditActivity.java
src/main/java/de/dennisguse/opentracks/ui/markers/MarkerEditViewModel.java

New marker get current location (on create rather than on save).

---

src/main/java/de/dennisguse/opentracks/chart/ChartView.java

If there is enough vertical space around each Y-axis marker then draw
them in two lines to free more horizontal space for the chart itself.
Fixes #1828

more compact Y-axis markers in charts

---

src/androidTest/java/de/dennisguse/opentracks/services/handlers/GpsStatusTest.java
src/main/java/de/dennisguse/opentracks/services/handlers/GPSManager.java
src/main/java/de/dennisguse/opentracks/services/handlers/GpsStatusManager.java
src/main/java/de/dennisguse/opentracks/settings/GpsSettingsFragment.java
src/main/java/de/dennisguse/opentracks/settings/PreferencesUtils.java
src/main/res/values/settings.xml
src/main/res/values/strings.xml
src/main/res/xml/settings_gps.xml

fix naming for the pace of reading of GPS location in settings

---

src/main/java/de/dennisguse/opentracks/data/models/ActivityType.java

The icon for kayaking activity is not the right one for some time.

Fix icon for kayaking activity

---

src/main/java/de/dennisguse/opentracks/AbstractActivity.java
src/main/java/de/dennisguse/opentracks/settings/PreferencesUtils.java
src/main/java/de/dennisguse/opentracks/settings/UserInterfaceSettingsFragment.java
src/main/res/values/settings.xml
src/main/res/values/strings.xml
src/main/res/values/styles_theme.xml

Fixes #1625.
~TODO: needs some trying if it works ;)~

UI: re-add OLED friendly (aka black) theme.

---

src/main/java/de/dennisguse/opentracks/services/announcement/VoiceAnnouncementUtils.java
src/main/java/de/dennisguse/opentracks/settings/PreferencesUtils.java
src/main/java/de/dennisguse/opentracks/util/StringUtils.java
src/main/res/values/settings.xml
src/main/res/values/strings.xml
src/main/res/xml/settings_announcements.xml

This pull request should fix #1805, while creating the option to enable or disable this type of announcement.
#1805

Setting to toggle distance/speed unit announcements

---

src/main/AndroidManifest.xml
src/main/java/de/dennisguse/opentracks/TrackListActivity.java
src/main/java/de/dennisguse/opentracks/TrackStoppedActivity.java
src/main/java/de/dennisguse/opentracks/ui/markers/MarkerListActivity.java
src/main/java/de/dennisguse/opentracks/ui/util/ActivityUtils.java
src/main/res/layout/marker_list.xml
src/main/res/layout/track_list.xml
src/main/res/menu/marker_list.xml
src/main/res/menu/track_list.xml

Predictive back: for everything except import/export.

---

src/androidTest/java/de/dennisguse/opentracks/stats/TrackStatisticsUpdaterTest.java
src/main/java/de/dennisguse/opentracks/data/models/TrackPoint.java
src/main/java/de/dennisguse/opentracks/stats/TrackStatistics.java
src/main/java/de/dennisguse/opentracks/stats/TrackStatisticsUpdater.java

Bug moving time#1756

---

src/main/java/de/dennisguse/opentracks/io/file/exporter/KMLTrackExporter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/KmlTrackImporter.java

Bugfix: KML 2.3 export must use heartrate as field name.

---

src/main/java/de/dennisguse/opentracks/ui/aggregatedStatistics/FilterDialogFragment.java
src/main/res/layout/fragment_filter_dialog.xml

Implemented using Material3's DatePicker.
Fixes #1681.

Aggregated stats: start of the week uses regional preferences (Android14+).

---

build.gradle

Fixes #1955.
This PR does NOT adjust the edge-to-edge situation.

Target Android 14/API34.

---

src/main/java/de/dennisguse/opentracks/settings/PreferencesUtils.java
src/main/java/de/dennisguse/opentracks/settings/UserInterfaceSettingsFragment.java
src/main/java/de/dennisguse/opentracks/util/IntentDashboardUtils.java
src/main/res/values-co/strings.xml
src/main/res/values-cs/strings.xml
src/main/res/values-de/strings.xml
src/main/res/values-es/strings.xml
src/main/res/values-fi/strings.xml
src/main/res/values-fr/strings.xml
src/main/res/values-ga/strings.xml
src/main/res/values-gl/strings.xml
src/main/res/values-hr/strings.xml
src/main/res/values-hu/strings.xml
src/main/res/values-kn/strings.xml
src/main/res/values-nb/strings.xml
src/main/res/values-nl/strings.xml
src/main/res/values-pt-rBR/strings.xml
src/main/res/values-pt-rPT/strings.xml
src/main/res/values-pt/strings.xml
src/main/res/values-ru/strings.xml
src/main/res/values-sl/strings.xml
src/main/res/values-tr/strings.xml
src/main/res/values-uk/strings.xml
src/main/res/values-vi/strings.xml
src/main/res/values-zh-rTW/strings.xml
src/main/res/values-zh/strings.xml
src/main/res/values/settings.xml
src/main/res/values/strings.xml
src/main/res/xml/settings_user_interface.xml

Dashboard API is nicer and easier.
Fixes #2012.
@pstorch what do you think about this change?

Removal of the "show on map"-feature using KML/GPX.

---

src/androidTest/java/de/dennisguse/opentracks/services/announcement/VoiceAnnouncementUtilsTest.java
src/main/java/de/dennisguse/opentracks/data/models/Track.java
src/main/java/de/dennisguse/opentracks/services/announcement/TTSManager.java
src/main/java/de/dennisguse/opentracks/services/announcement/VoiceAnnouncementManager.java
src/main/java/de/dennisguse/opentracks/services/announcement/VoiceAnnouncementUtils.java
src/main/java/de/dennisguse/opentracks/settings/PreferencesUtils.java
src/main/java/de/dennisguse/opentracks/stats/TrackStatistics.java
src/main/res/values/settings.xml
src/main/res/xml/settings_announcements.xml

Announcements: added current time.

---

build.gradle

Gradle: fix deprecations (for Gradle 9).

---

src/main/java/de/dennisguse/opentracks/data/models/TrackPoint.java
src/main/java/de/dennisguse/opentracks/sensors/sensorData/AggregatorGPS.java
src/main/java/de/dennisguse/opentracks/services/handlers/TrackPointCreator.java

Likely introduced b9ed5e28e02d88b5a9b6e3861409fd682ad0f7fa.
(If available): The link to the issue that this pull …

Bugfix: GPS-based data in UI should not drop back to zero.

---

README_TESTED_SENSORS.md

Added Decathlon HRM as a tested HRM device
