src/main/java/de/dennisguse/opentracks/services/tasks/AnnouncementPeriodicTask.java

Revert the duration hint passed to `requestAudioFocus` to `AUDIOFOCUS_GAIN_TRANSIENT_MAY_DUCK` and pass `audioFocusChangeListener` to `abandonAudioFocus`.
Starting the following commit: https://github.com/dennisguse/OpenTracks/commit/d1a459efc2417d6c0bf3490459228ec4b19fff1b the duration hint was changed from `AUDIOFOCUS_GAIN_TRANSIENT_MAY_DUCK` to `AUDIOFOCUS_GAIN_TRANSIENT`.
This introduced the behavior that OpenTracks stops audio players when doing the voice announcement, after the announcement was finished the audio player however didn't resume playing and required manual intervention.
IMO the voice announcement shouldn't stop your music since it is annoying and definitely against what the user expects. Ducking the volume, as it was < `v3.2.9`, is the better option.
(In my case - using …

Revert duration hint to MAY_DUCK

---

src/main/java/de/dennisguse/opentracks/fragments/FileTypeDialogFragment.java
src/main/java/de/dennisguse/opentracks/io/file/TrackFileFormat.java
src/main/res/values-de/strings.xml
src/main/res/values-es/strings.xml
src/main/res/values/strings.xml

Solves #17 
Before:
All as KMZ to <>
All as KML to <>
All as GPX to <>
After:
All as KMZ (with photos) to <>
All as KMZ (without photos) to <>
All as KML (without photos)  to <>
All as GPX (without photos) to <>
There's likely a more idiomatic way to do this, I also did not do any testing on the added file format (KMZ_WITH_TRACKDETAIL_AND_SENSORDATA) but can do that later if needed

Added KMZ without photos, photo details to export menu

---

src/main/res/values/settings.xml
src/main/res/xml/settings.xml

Fixes #163.
Added an `android:key` in `PreferenceCategory` with expandable (advanced settings). Without `android:key` logcat fire an error.
https://github.com/OpenTracksApp/OpenTracks/issues/163

Add android:key in PreferenceCategory with expandable.

---

src/main/java/de/dennisguse/opentracks/fragments/MarkerDetailFragment.java
src/main/java/de/dennisguse/opentracks/util/IntentUtils.java
src/main/res/menu/marker_detail.xml
src/main/res/values-b+es+419/strings.xml
src/main/res/values-ca/strings.xml
src/main/res/values-es/strings.xml
src/main/res/values/strings.xml

Fixes #89.
I added a new menu option in `MarkerDetailFragment` that only is visible in markers with photo/image. This option can be used to share the photo/image of a marker.
Also, I added new strings in english, spanish and catalan languages for images shared (a subject and a text).
I would like to point out a issue that I think you have to think about: 
I would like to point out an issue that I think you have to think about: I've added a new method in IntentUtils that can be used to share an image but nobody avoid that somebody use this method for share any other file because the only thing it needs is a URI (and an URI can be any kind of file). Do you think, this method should be test that URI is a file before to share, something like that:
```
public …
```

Share pictures from marker.

---

src/androidTest/java/de/dennisguse/opentracks/content/DescriptionGeneratorTest.java
src/main/java/de/dennisguse/opentracks/content/DescriptionGenerator.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/KmlTrackWriter.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/KmzTrackExporter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/AbstractFileTrackImporter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/ImportAsyncTask.java
src/main/java/de/dennisguse/opentracks/io/file/importer/KmzTrackImporter.java
src/main/java/de/dennisguse/opentracks/stats/TrackStatistics.java
src/main/java/de/dennisguse/opentracks/util/FileUtils.java

**For KMZ importer**
- First: It reads the images inside KMZ file and copy them to OpenTracks external storage.
- Second: It parses doc.kml that is inside KMZ file checking that href in waypoint's tag points to an existing image in OpenTracks storage. If exists it creates a marker with photo. Otherwise only the marker.
It needs to open two times KMZ file. The first one to find images and the second one to parses doc.kml inside KMZ.
**For KMZ exporter**
- It creates the waypoint with image in the doc.kml file only if this image exists inside OpenTracks external storage. Otherwise it creates the waypoint in the doc.kml file without href.
- When it generates description for kml file it adds min/max elevation only if these data are valid.
- Added tests for this last point.
**A little bug** …

Improve import/export

---

src/androidTest/java/de/dennisguse/opentracks/util/TrackPointUtilsTest.java
src/main/java/de/dennisguse/opentracks/util/TrackPointUtils.java
src/main/java/de/dennisguse/opentracks/util/UnitConversions.java

https://en.wikipedia.org/wiki/GPS_Week_Number_Rollover
https://github.com/OpenTracksApp/OpenTracks/issues/155

Workaround for GPS week rollover (happening every 19.7 years).

---

src/androidTest/java/de/dennisguse/opentracks/content/data/TestDataUtil.java
src/androidTest/java/de/dennisguse/opentracks/content/provider/CustomContentProviderUtilsTest.java
src/main/java/de/dennisguse/opentracks/content/provider/ContentProviderUtils.java
src/main/java/de/dennisguse/opentracks/fragments/DeleteMarkerDialogFragment.java
src/main/java/de/dennisguse/opentracks/io/file/importer/KmzTrackImporter.java
src/main/java/de/dennisguse/opentracks/util/FileUtils.java

Fixes two bugs:
- When a track with waypoint's photos was deleted, the folder with these photos weren't deleted.
- When a waypoint with a photo was deleted, the photo wasn't deleted.
These two bugs resulted in waste of external storage with the remaining files photos.
Also, I've added some new tests:
- All tracks are delete (with waypoint's photo): checks that all folders with waypoint's photos from tracks deleted are deleted from external storage.
- Delete a track (with waypoint's photo): checks that track's deleted folder is deleted but not the others tracks.
- Delete waypoint (with photo): checks that the waypoint's photo is delete too.
With these tests (I hope) any change about deleting tracks/waypoints in the code guarantee that will be well done.
**Link …

Images/folders are deleted when tracks/waypoints are deleted. This fixes #189.

---

src/main/java/de/dennisguse/opentracks/services/TrackRecordingService.java

When a recording starts it sets a name with started date time.
When recording ends It's not needed to set the name, only sets the name if track's name is empty or null.
Maybe all the code that sets a name in endCurrentTrack can be removed. In fact, I think is unnecessary. Anyway, if "something" between start and stop recording would set a null name then this would correct it.
https://github.com/OpenTracksApp/OpenTracks/issues/209

While track is recording user can change the name.

---

src/androidTest/java/de/dennisguse/opentracks/content/provider/CustomContentProviderUtilsTest.java
src/main/java/de/dennisguse/opentracks/MarkerEditActivity.java
src/main/java/de/dennisguse/opentracks/content/provider/ContentProviderUtils.java

When user edits a marker and deletes the photo from marker then this photo is deleted from storage too. This Fixes #208.
https://github.com/OpenTracksApp/OpenTracks/issues/208

Edit marker: if user deletes photo then photo is deleted from storage too.

---

src/main/java/de/dennisguse/opentracks/AboutActivity.java
src/main/java/de/dennisguse/opentracks/HelpActivity.java
src/main/java/de/dennisguse/opentracks/util/ViewUtils.java
src/main/res/layout/about.xml

Links already clickable. I've tested it in API 21 and API 29.
With android:autoLink="web" in xml layout only links like this works:
`https://github.com/OpenTracksApp/OpenTracks`
but not links like this:
`<a href="https://github.com/OpenTracksApp/OpenTracks">OpenTracks</a>`
So I've decided to use `setMovementMethod` method on `TextView` with links.
#232 

Settings/Help: links are clickable. Fixes #232.

---

build.gradle
src/androidTest/java/de/dennisguse/opentracks/content/provider/ShareContentProviderTest.java
src/main/AndroidManifest.xml
src/main/java/de/dennisguse/opentracks/ShowOnMapProxyActivity.java
src/main/java/de/dennisguse/opentracks/TrackListActivity.java
src/main/java/de/dennisguse/opentracks/TrackRecordedActivity.java
src/main/java/de/dennisguse/opentracks/TrackRecordingActivity.java
src/main/java/de/dennisguse/opentracks/content/provider/ContentProviderUtils.java
src/main/java/de/dennisguse/opentracks/content/provider/ShareContentProvider.java
src/main/java/de/dennisguse/opentracks/util/IntentDashboardUtils.java
src/main/java/de/dennisguse/opentracks/util/IntentUtils.java
src/main/res/values/strings.xml

As of Android R querying for installed applications is limited (I love this change).
However, we used this functionality for _show on map_.
So far, we check if OSMDashboard is installed (implicit intent) using this feature and if it was not installed, we were falling back to KMZ.
I changed this, so that we OpenTracks provides a "Open as KMZ" activity that takes the provided DashboardAPI URIs to actual KMZ URIs that are hosted by the ShareContentProvider.
When this activity is selected in the IntentChooser for the DashboardAPI, it creates a new IntentChooser for KMZ.
Works like charm in the emulator and on Android 9.
Nitpick: whenever you want to open OSMDashboard now always a IntentChooser is presented.

Upgrade to Android R (API 30)

---

.idea/misc.xml
src/androidTest/java/de/dennisguse/opentracks/viewmodels/AggregatedStatisticsTest.java
src/main/AndroidManifest.xml
src/main/java/de/dennisguse/opentracks/AggregatedStatisticsActivity.java
src/main/java/de/dennisguse/opentracks/TrackListActivity.java
src/main/java/de/dennisguse/opentracks/adapters/AggregatedStatisticsAdapter.java
src/main/java/de/dennisguse/opentracks/util/StringUtils.java
src/main/java/de/dennisguse/opentracks/viewmodels/AggregatedStatistics.java
src/main/java/de/dennisguse/opentracks/viewmodels/AggregatedStatisticsModel.java
src/main/res/drawable/ic_statistics_24dp.xml
src/main/res/layout/aggregated_stats.xml
src/main/res/layout/aggregated_stats_list_item.xml
src/main/res/menu/track_list.xml
src/main/res/values/styles.xml

Added new Activity that shows aggregated statistics by activity type.
I've used ViewModel and LiveData to load aggregated stats from database in a ListView. Also, I've used a custom adapter to that ListView for handle different types of sports.
It shows for now:
- Number of activities per sport type.
- Total distance and time per sport type.
- Avg. speed or Avg. pace per sport type.
- Max. speed or Fastest pace per sport type.
In the future this Activity could be three tabs: one for all times stats, other one for monthly stats and last one for yearly stats. But for the first version I think it's enough for now.
I've added tests for new AggregatedStatistics class.
And, an screenshot: …

Aggregated statistics by activity type.

---

src/androidTest/java/de/dennisguse/opentracks/content/data/TestDataUtil.java
src/androidTest/java/de/dennisguse/opentracks/io/file/importer/ExportImportTest.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/GpxTrackWriter.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/KmlTrackWriter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/AbstractFileTrackImporter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/GpxFileTrackImporter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/KmlFileTrackImporter.java
src/main/res/values/strings.xml

Adds speed into GPX and KML files when exporting.
When importing a GPX/KML file with speed all #275 issues are fixed but the total time. Total time in export/import process seem be always less than real total time. That's because of #192.
These data are the same when you export and import:
- Distance.
- Moving time.
- Max. Speed.
- Avg. Speed.
The only thing is not fixed is the total time.
https://github.com/OpenTracksApp/OpenTracks/issues/300

Import/Export speed in GPX and KML files.

---

src/main/java/de/dennisguse/opentracks/AggregatedStatisticsActivity.java
src/main/java/de/dennisguse/opentracks/adapters/AggregatedStatisticsAdapter.java

Aggregated stats didn't use Preferred Rate from Preferences. This was not coherent. Fixed in this PR.
By the way, I've changed the observer from Anonymous class to Lambda expression.
#321 

Preferred rate is used for aggregated stats

---

src/main/AndroidManifest.xml
src/main/java/de/dennisguse/opentracks/content/data/WaypointsColumns.java
src/main/java/de/dennisguse/opentracks/content/provider/CustomContentProvider.java
src/main/java/de/dennisguse/opentracks/util/IntentDashboardUtils.java

Necessary for https://github.com/OpenTracksApp/OSMDashboard/issues/48
Exposes the waypoints URI for the Dashboard and makes MarkerDetailActivity callable via Intent.

expose waypoints to dashboard

---

src/main/java/de/dennisguse/opentracks/services/TrackRecordingServiceConnection.java
src/main/java/de/dennisguse/opentracks/util/ServiceUtils.java

Always start the service as we cannot check (anymore) if a service is actually running.
Actually, we can, but we should not.
I guess, it was a memory/performance optimization.
Reworking GPSStatus will remove ServiceUtils completely.

TrackRecordingServiceConnection

---

src/androidTest/java/de/dennisguse/opentracks/content/SearchEngineTest.java
src/androidTest/java/de/dennisguse/opentracks/io/file/importer/ExportImportTest.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/GpxTrackWriter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/AbstractFileTrackImporter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/GpxFileTrackImporter.java

This is a breaking change as speed exported with v3.7.6 cannot be imported.
Fixes #181.
Follow-up to #336.
@ronajon i fixed some smaller things (added missing members to AbstractFileImporter, enabled the tests, and changed speed to also use TrackPointExtension/v2.)
Well prepared :+1: 
It was just easier for to create a branch in the main repo...

GPX: export heartrate, cadence, and speed via TrackPointExtension/v2

---

src/main/java/de/dennisguse/opentracks/MarkerEditActivity.java

When you are editing a marker with a photo, click on photo delete button and change the orientation the delete button is not hidden.
To reproduce:
- Click on track with a marker with photo.
- Click on track menu -> markers.
- Click on marker with photo.
- Click on menu -> edit.
- Click on delete button on photo.
- Photo and button vanish.
- Change the orientation.
- The delete button is shown but the image is hidden.

Orientation change: editing marker with photo.

---

src/androidTest/java/de/dennisguse/opentracks/content/SearchEngineTest.java
src/main/java/de/dennisguse/opentracks/content/provider/ContentProviderUtils.java
src/main/java/de/dennisguse/opentracks/content/provider/CustomContentProvider.java
src/main/java/de/dennisguse/opentracks/content/provider/CustomSQLiteOpenHelper.java

Here is a draft for SearchEngineTest using a separate database that is deleted after each test.

Tests should not use production database

---

src/main/java/de/dennisguse/opentracks/fragments/ExportProgressDialogFragment.java

OpenTracks cracked when you tried to export.
In `ExportProgressDialogFragment` Track.Id is used to create the file name:
```java
String fileName = track.getId() + "." + trackFileFormat.getExtension();
```
So here the code is trying to convert to string the Track.Id object that trigger a `RuntimeException` with "Not supported".

Bugfix: export all failed trying to convert to string the Track.Id.

---

src/main/java/de/dennisguse/opentracks/services/handlers/LocationHandler.java

Location handler didn't unregister location listener.
https://github.com/OpenTracksApp/OpenTracks/issues/403

Bugfix: location handler didn't remove updates.

---

src/main/java/de/dennisguse/opentracks/TrackRecordingActivity.java
src/main/java/de/dennisguse/opentracks/fragments/IntervalsRecordedFragment.java
src/main/java/de/dennisguse/opentracks/fragments/IntervalsRecordingFragment.java
src/main/java/de/dennisguse/opentracks/viewmodels/IntervalStatisticsModel.java
src/main/java/de/dennisguse/opentracks/views/IntervalListView.java

Recorded activity didn't initialize the intervals. Also, invalidate didn't work in view model.
Recording activity didn't show intervals because the activity passed a null Track.Id because the Track.Id is created in the Runnable for new tracks. Now interval fragment listen for a new Track.Id. I've kept the argument in newInstance because we don't know if Runnable finished before fragment is created, right? *I don't know if this is the best approach so I create a Draft PR.*
Finally, unit changed must result in a interval refreshing.
https://github.com/OpenTracksApp/OpenTracks/issues/406

Fixed some intervals issues.

---

src/androidTest/java/de/dennisguse/opentracks/util/StringUtilsTest.java
src/main/java/de/dennisguse/opentracks/util/StringUtils.java

10.1km/h instead of 10.19km/h.
Having two decimal digits suggests a precision that GPS will anyhow not provide.
I guess cycling speed sensors won't as well.
Collected data is still stored with "full" precision.

Present speed only with one fractional digit.

---

src/androidTest/java/de/dennisguse/opentracks/content/data/TestDataUtil.java
src/androidTest/java/de/dennisguse/opentracks/viewmodels/IntervalStatisticsTest.java
src/main/java/de/dennisguse/opentracks/TrackRecordedActivity.java
src/main/java/de/dennisguse/opentracks/TrackRecordingActivity.java
src/main/java/de/dennisguse/opentracks/adapters/IntervalStatisticsAdapter.java
src/main/java/de/dennisguse/opentracks/content/TrackDataHub.java
src/main/java/de/dennisguse/opentracks/fragments/IntervalsFragment.java
src/main/java/de/dennisguse/opentracks/viewmodels/IntervalStatistics.java
src/main/java/de/dennisguse/opentracks/viewmodels/IntervalStatisticsModel.java
src/main/res/drawable/ic_arrow_drop_up_24.xml
src/main/res/layout/interval_list_view.xml
src/main/res/layout/interval_stats_list_item.xml

Intervals show distance, speed/pace (depending on user's settings) and gain.
I would like to test it in real activities (I hope next week) to move this Draft to PR.
**Motivation**
Speed or pace doesn't mean too much without gain. For example, an average speed of 10km/h by bike in an interval of 1km can seem too little but if you has a gain of 80m then 10km/h is so good.
That's why I think is necessary the gain in intervals.
PS/ When we add elevation loss to the logic of OpenTracks then we'll been able to add the elevation lost too.
By opening this pull request, you are providing your contribution under the _Apache License 2.0_ (see …

Intervals rate and gain

---

src/main/res/layout/marker_edit.xml
src/main/res/layout/track_edit.xml

Some releases ago, every time you clicked on an EditText the text was selected (selectAllOnFocus) and text were capitalized by word or by sentence.
After this PR:
- For titles: added attributes textCapWords and selectAllOnFocus.
- For descriptions: added attributes textCapSentences and selectAllOnFocus.
I think this should be the default behaviour.
#461 

Edit texts: select all on focus and capitalize by words/sentences.

---

src/androidTest/java/de/dennisguse/opentracks/content/SearchEngineTest.java
src/androidTest/java/de/dennisguse/opentracks/content/provider/CustomContentProviderUtilsTest.java
src/androidTest/java/de/dennisguse/opentracks/content/provider/CustomSQLiteOpenHelperTest.java
src/androidTest/java/de/dennisguse/opentracks/io/file/importer/ExportImportTest.java
src/main/java/de/dennisguse/opentracks/content/data/Marker.java
src/main/java/de/dennisguse/opentracks/content/data/MarkerColumns.java
src/main/java/de/dennisguse/opentracks/content/data/TrackPointsColumns.java
src/main/java/de/dennisguse/opentracks/content/provider/ContentProviderUtils.java
src/main/java/de/dennisguse/opentracks/content/provider/CustomContentProvider.java
src/main/java/de/dennisguse/opentracks/content/provider/CustomSQLiteOpenHelper.java

So far the three tables were independent of each other (from a database perspective).
I added now foreign key constraints incl. cascading deletes for trackId.
Thus, if a track get's deleted the database automatically deletes all referencing trackpoints and marker automatically.
However, this has a drawback: There is only _one_ notification for consent observer (i.e., the track got deleted). So far, we sent one for each trackpoint and marker as well.
Also the trackId column is now NOT NULL.

Database enforces foreign key constraints incl. cascading deletes.

---

src/main/java/de/dennisguse/opentracks/TrackDeleteActivity.java
src/main/java/de/dennisguse/opentracks/content/provider/ContentProviderUtils.java
src/main/java/de/dennisguse/opentracks/io/file/importer/AbstractFileTrackImporter.java

After #480 got implemented, we can now delete multiple tracks in one go and only cause DB vacuum once.

optimize multiple track deletion

---

src/main/java/de/dennisguse/opentracks/io/file/importer/DirectoryChooserActivity.java

I tested the bug on emulater with android 11. The problem didn't happen with OSMDashboard, so I compared the code and found some differences.
@rgmf @dennisguse Please have a look.

fix #491 crash export on android 11

---

README_TESTED_SENSORS.md

Adds three tested sensors
* "Polar H10" heart rate sensor
* "Garmin Cadence Sensor 2" cadence sensor
* "Garmin Speed Sensor 2" speed sensor
As discussed in https://github.com/OpenTracksApp/OpenTracks/pull/444
I didn't want to change unrelated lines in the file but vscode told me the Markdown should probably have empty lines around the lists

Update list of tested sensors with Polar H10 and Garmin SPD/CAD

---

src/main/java/de/dennisguse/opentracks/io/file/importer/ImportActivity.java

I cannot reproduce the #506 issue but it's clear that `summary` can be NULL if user press back button before view model load import data.

Bugfix: NPE in import. Fixes #506.

---

build.gradle
proguard-rules.txt

We can save quite some space by using shrinking the APK (removing unused things; I guess mainly support library stuff) without obfuscation.
Merge after next release.
Needs some serious testing...
Fixes #433.

Shrinking all APK builds without obfuscation.

---

src/main/java/de/dennisguse/opentracks/content/data/Track.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingService.java
src/main/java/de/dennisguse/opentracks/settings/SettingsActivity.java
src/main/java/de/dennisguse/opentracks/util/ExportUtils.java
src/main/res/values/strings.xml

Change the post workout export to use the ExportService (JobIntentService) and directing the user to the SettingsActivity in case the export failed to check the export directory.

fix #516 post workout export fails silently

---

src/main/java/de/dennisguse/opentracks/content/provider/ContentProviderUtils.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/KmlTrackWriter.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/KmzTrackExporter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/AbstractFileTrackImporter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/ImportAlreadyExistsException.java
src/main/java/de/dennisguse/opentracks/io/file/importer/KmzTrackImporter.java
src/main/res/values/strings.xml

I've coded option 1 (import in two steps) and option 4 (import in memory). I like the best option 4 and I think OOM risk is really hard. Why do I think it's difficult or impossible? I have a 900km track (more than 10 hours recording) and it has a size of 8MB in gpx file. I cannot imagine a 10 times longer track, for instance. But, even in that case the file would be 80MB size.
Also, when we'll support several tracks in an only file we have to know that this method load track one by one, so here isn't a problem either.
I also tried to figure out how options 2 and 3 would be, but for me it was difficult (maybe I don't have the needed knowledge), I didn't see it very clearly.
PS/ Don't hesitate to throw this PR away if you think memory import can be problematic ;)
That said. Here you have a …

Optimize import (pstorch's option 4)

---

src/main/java/de/dennisguse/opentracks/settings/SettingsActivity.java
src/main/java/de/dennisguse/opentracks/settings/bluetooth/BluetoothLeSensorPreference.java
src/main/java/de/dennisguse/opentracks/util/BluetoothUtils.java

Some BLE devices do not announce all there supported services in the BLE advertisement packages.
Android's ScanFilter decides based upon this information only.
When connecting to such a device (and trigger service discovery), the service can still be used.
Fixes #447.

BLE sensors: Miband3's is now considered a heart rate sensor during discovery

---

src/main/java/de/dennisguse/opentracks/AbstractActivity.java
src/main/java/de/dennisguse/opentracks/MarkerListActivity.java
src/main/java/de/dennisguse/opentracks/TrackListActivity.java
src/main/java/de/dennisguse/opentracks/settings/SettingsActivity.java
src/main/res/layout/toolbar.xml

The app icon is now only shown in the TrackListActivity.
In all other activities the actionBar icon now triggers the back action (same as Android navigation bar).
This feature was actually in place quite a while ago, but implemented differently.
Back then the actual target for the back action of each activity was defined in the manifest.
The new solution just uses android's activity stack to go back.

ActionBar now provides back functionality

---

src/main/java/de/dennisguse/opentracks/MarkerEditActivity.java
src/main/java/de/dennisguse/opentracks/content/data/Marker.java
src/main/java/de/dennisguse/opentracks/viewmodels/MarkerEditViewModel.java

MarkerEditActivity had a lot of logic, specially with photo handle. This is my proposal to move the logic from Activity to ViewModel.
Activity:
- Handle the views.
- Send/Receive data changes to/from ViewModel.
ViewModel:
- Handle Marker object (I've created a new Marker's constructor - is it a good idea?).
- Save photo on internal OT storage and clean orphan files.
- Insert the Marker through Service.
MarkerEditActivity <--------> MarkerEditViewModel <---------> Marker
It's a proposal... I'm not too much sure this is the best option but I don't know what other options there are either.

Refactoring MarkerEditActivity. Logic has been moved to a ViewModel.

---

src/main/java/de/dennisguse/opentracks/MarkerListActivity.java
src/main/java/de/dennisguse/opentracks/fragments/MarkerDetailFragment.java
src/main/java/de/dennisguse/opentracks/util/IntentUtils.java

Marker images can now be shared from the list directly via the contet menu (like tracks).
Fixes #495.

Share markers from list

---

src/androidTest/java/de/dennisguse/opentracks/content/data/TestDataUtil.java
src/androidTest/java/de/dennisguse/opentracks/io/file/importer/ExportImportTest.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/GpxTrackWriter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/AbstractFileTrackImporter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/GpxFileTrackImporter.java

OT lost elevation gain/loss after export and import process. Fixed.
I've added `<opentracks:gain>` and `<opentracks:loss>` tags from  to GPX files.
#555 

Added opentracks:gain and opentracks:loss information in GPX files

---

src/androidTest/java/de/dennisguse/opentracks/content/data/TestDataUtil.java
src/androidTest/java/de/dennisguse/opentracks/content/provider/CustomContentProviderUtilsTest.java
src/androidTest/java/de/dennisguse/opentracks/io/file/importer/ExportImportTest.java
src/androidTest/java/de/dennisguse/opentracks/services/TrackRecordingServiceTest.java
src/androidTest/java/de/dennisguse/opentracks/services/TrackRecordingServiceTestLooper.java
src/androidTest/java/de/dennisguse/opentracks/util/AnnouncementUtilsTest.java
src/androidTest/java/de/dennisguse/opentracks/viewmodels/IntervalStatisticsTest.java
src/main/java/de/dennisguse/opentracks/TrackEditActivity.java
src/main/java/de/dennisguse/opentracks/adapters/SensorsAdapter.java
src/main/java/de/dennisguse/opentracks/content/TrackDataHub.java
src/main/java/de/dennisguse/opentracks/content/data/Marker.java
src/main/java/de/dennisguse/opentracks/content/data/Track.java
src/main/java/de/dennisguse/opentracks/content/data/TrackPoint.java
src/main/java/de/dennisguse/opentracks/content/provider/ContentProviderUtils.java
src/main/java/de/dennisguse/opentracks/content/provider/TrackPointIterator.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/FileTrackExporter.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/KmlTrackWriter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/AbstractFileTrackImporter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/KmzTrackImporter.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingService.java

isValid() should not be necessary.
We can just use null as Track.Id or Marker.Id if the marker/track was not loaded from the database.

Remove Track.Id and Marker.Id.isValid()

---

src/main/java/de/dennisguse/opentracks/io/file/exporter/ExportActivity.java
src/main/java/de/dennisguse/opentracks/io/file/importer/ImportActivity.java
src/main/java/de/dennisguse/opentracks/io/file/importer/ImportViewModel.java
src/main/res/layout/export_activity.xml
src/main/res/layout/import_activity.xml
src/main/res/values-cs/strings.xml
src/main/res/values-es/strings.xml
src/main/res/values-gl/strings.xml
src/main/res/values-it/strings.xml
src/main/res/values-nb/strings.xml
src/main/res/values-pt-rBR/strings.xml
src/main/res/values/strings.xml
src/main/res/values/styles.xml

*ImportActivity/ExportActivity UI improvements (summary messages)*
Summary messages have been improved offering only useful information. It doesn't make sense these Activity show to the user something like this:
```
- Files imported: 10
- Already exists: 0
- Errors: 0
```
The best option, in this case, should be:
```
Files imported: 10
```
*ImportActivity offers the option to open a track imported*
#558 makes sense. If user import only one file it would interesting to offers to the user to open the track just imported to see the details straight away.
**Screenshots**
#558 

Import/Export UI improvement and offer "Open Track" when one track is imported

---

src/main/java/de/dennisguse/opentracks/MarkerDetailActivity.java

MarkerDetail accepts Marker.Id also as `long`.

---

src/androidTest/java/de/dennisguse/opentracks/content/sensor/SensorDataCyclingTest.java
src/main/java/de/dennisguse/opentracks/adapters/SensorsAdapter.java
src/main/java/de/dennisguse/opentracks/content/provider/ContentProviderUtils.java
src/main/java/de/dennisguse/opentracks/content/sensor/SensorData.java
src/main/java/de/dennisguse/opentracks/content/sensor/SensorDataCycling.java
src/main/java/de/dennisguse/opentracks/content/sensor/SensorDataCyclingPower.java
src/main/java/de/dennisguse/opentracks/content/sensor/SensorDataHeartRate.java
src/main/java/de/dennisguse/opentracks/content/sensor/SensorDataSet.java
src/main/java/de/dennisguse/opentracks/fragments/StatisticsRecordedFragment.java
src/main/java/de/dennisguse/opentracks/fragments/StatisticsRecordingFragment.java
src/main/java/de/dennisguse/opentracks/stats/SensorStatistics.java
src/main/java/de/dennisguse/opentracks/viewmodels/SensorDataModel.java
src/main/res/layout/statistics_recorded.xml
src/main/res/values/strings.xml

**Context**
OT saves on trackpoints table sensor information: heart rate, cadence and power. But users cannot see sensor stats after recording an activity, they were hidden.
**Description**
Track recorded stats now shows sensor data stats from trackpoints table:
- Heart rate: maximum and average.
- Cadence: maximum and average.
- Power: average.
**Changes impact on other parts**
I've generalized SensorsAdapter so it can be used from track recorded and track recording activities. This adapter can be used from sensors classes and from new SensorStats class whose data comes from trackpoints table.
For that, I've created a model for SensorsAdapter.
**Some screenshots**
**Issues related**
#525 and #502 and #214
By opening this pull request, you are providing your …

Track recorded stats shows sensor data from trackpoints table

---

src/androidTest/java/de/dennisguse/opentracks/content/data/TestSensorDataUtil.java
src/androidTest/java/de/dennisguse/opentracks/content/provider/CustomContentProviderUtilsTest.java
src/main/java/de/dennisguse/opentracks/content/data/TrackPointsColumns.java
src/main/java/de/dennisguse/opentracks/content/data/TracksColumns.java
src/main/java/de/dennisguse/opentracks/content/provider/ContentProviderUtils.java
src/main/java/de/dennisguse/opentracks/content/provider/CustomContentProvider.java
src/main/java/de/dennisguse/opentracks/stats/SensorStatistics.java

It computes time weighted heart rate, cadence and power averages. So the more time it takes the more important is.
Also, it computes heart rate and cadence maximum.
Finally, it ignores pause time for whatever reason (SEGMENT_START_MANUAL, SEGMENT_START_AUTOMATIC).
For a track with about 7000 trackpints the query takes about 140ms.
#601 

Normalize hr, cadence and power averages

---

src/main/java/de/dennisguse/opentracks/TrackListActivity.java
src/main/java/de/dennisguse/opentracks/TrackRecordedActivity.java
src/main/java/de/dennisguse/opentracks/fragments/StatisticsRecordedFragment.java
src/main/res/layout/sensor_item.xml
src/main/res/layout/statistics_recorded.xml
src/main/res/values/do_not_translate.xml
src/main/res/values/styles.xml

Following up #566 I've re-design stats recorded fragment layout:
- Added name, description and start datetime.
- Moving stats are primary (total time and avg. speed are secondary).
- Sensor units next to their values instead of behind them (like the others stats).
There are UI changes so this PR is open for discussion. I've put the focus on moving stats because I consider that they are the more important one. On the other hand, IMHO all stats are equally important so all of them use Large values and labels.
**Screenshots**
#566 

Recorded fragment shows name, desc, start datetime.

---

src/androidTest/java/de/dennisguse/opentracks/util/ExportUtilsTest.java
src/main/java/de/dennisguse/opentracks/content/data/Track.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/ExportActivity.java
src/main/java/de/dennisguse/opentracks/util/ExportUtils.java

Exported track's name like proposed in #512 (see comment: https://github.com/OpenTracksApp/OpenTracks/issues/512#issuecomment-766437523)
Also, it checks if file that result of export process match with the following regular expression:
`<UUID first 8 bytes>.*\.<extension>`
PS/ If it is accepted I'd like to add/update tests, but I need to be sure that it's what was expected in #512.
#512

Track exported names: UUID, track's name and extension

---

src/androidTest/java/de/dennisguse/opentracks/io/file/importer/ExportImportTest.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/GPXTrackExporter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/AbstractFileTrackImporter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/GpxFileTrackImporter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/KmlFileTrackImporter.java

Uses Garmin extensions to export power data.
This is compatible with Golden Cheetah.
This is NOT supported by Strava.
They would require to use "power" instead of "PowerInWatts"./
See https://developers.strava.com/docs/uploads/
Fixes #638.

GPX: export and import power data.

---

src/main/res/values/settings.xml

Show the coordinates by default, so new users are aware that they can get them if needed.

While recording show coordinates by default.

---

src/main/java/de/dennisguse/opentracks/services/sensors/AltitudeSumManager.java

`sensorManager.registerListener` didn't work because `samplingPeriodUs` arguments was in nanosecons. Seem that delay must be in microseconds. According to the documentation:
The rate `android.hardware.SensorEvent sensor events` are delivered at. This is only a hint to the system. Events may be received faster or slower than the specified rate. Usually events are received faster. The value must be one of `#SENSOR_DELAY_NORMAL`, ` #SENSOR_DELAY_UI`, `#SENSOR_DELAY_GAME`, or `#SENSOR_DELAY_FASTEST` or, the desired delay between events in microseconds. Specifying the delay in microseconds only works from Android 2.3 (API level 9) onwards. For earlier releases, you must use one of the `SENSOR_DELAY_*` constants.
So, I propose to use SENSOR_DELAY_FASTEST.
**Link to …

registerListener for barometric sensor uses SENSOR_DELAY_FASTEST

---

src/main/java/de/dennisguse/opentracks/content/data/Distance.java
src/main/java/de/dennisguse/opentracks/viewmodels/IntervalStatisticsModel.java

@dennisguse maybe we need a new release because intervals are computed using 1m, 2m, 5m, 10m, 20m, 50m instead of 1km, 2km, 5km, 10km, 20km, 50km.
Sorry, but I couldn't test new Distance code until now :(
This PR fixes that.

Distance interval bugfixed: interval options are km/mi values

---

src/main/java/de/dennisguse/opentracks/services/tasks/AnnouncementPeriodicTask.java

`announce` should be called after getting `recordingTrackId`.
Also, if `track` is null then `announce` should be stopped (announcement cannot be used).

Announcement potencial bug and race condition fixed.

---

src/main/java/de/dennisguse/opentracks/services/TrackRecordingService.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingServiceStatus.java
src/main/java/de/dennisguse/opentracks/services/tasks/AnnouncementPeriodicTask.java
src/main/java/de/dennisguse/opentracks/stats/TrackStatisticsUpdater.java

Related to #719, but does not (yet) fix the memory leak.
We need to make sure this is executed by every listener.
```
TrackRecordingService.removeListener()
```

Bugfix: AnnouncementPeriodicTask does register at TrackRecordingServiceListener

---

src/main/java/de/dennisguse/opentracks/fragments/StatisticsRecordedFragment.java

`loadStatistics` called to `onSharedPreferenceChanged` before `this.track = track` assignment.
Also, track cannot be null on `StatisticsRecordedFragment`. In that case Activity finishes and print onto logs.
#726

Bugfix: track stats always show pace

---

src/androidTest/java/de/dennisguse/opentracks/chart/ChartPointTest.java
src/androidTest/java/de/dennisguse/opentracks/fragments/ChartFragmentTest.java
src/main/java/de/dennisguse/opentracks/AbstractListActivity.java
src/main/java/de/dennisguse/opentracks/TrackRecordedActivity.java
src/main/java/de/dennisguse/opentracks/TrackRecordingActivity.java
src/main/java/de/dennisguse/opentracks/chart/ChartPoint.java
src/main/java/de/dennisguse/opentracks/content/TrackDataHub.java
src/main/java/de/dennisguse/opentracks/content/TrackDataListener.java
src/main/java/de/dennisguse/opentracks/content/TrackDataManager.java
src/main/java/de/dennisguse/opentracks/fragments/ChartFragment.java
src/main/java/de/dennisguse/opentracks/fragments/IntervalsFragment.java
src/main/java/de/dennisguse/opentracks/fragments/StatisticsRecordedFragment.java
src/main/java/de/dennisguse/opentracks/fragments/StatisticsRecordingFragment.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingService.java
src/main/java/de/dennisguse/opentracks/stats/TrackStatistics.java

Does not fix #719.
TrackDataHub does not need to register for TrackRecordingService status changes as this can be handled by TrackRecordingActivity alone.
* reduces impact of memory leak as TrackDataHub keeps references to fragments; now only the activities are referenced by TrackRecordingServices and those at least remove all there references.
* (so far) TrackDataHub started TrackRecordingSevice due to binding to the service (even if only showing already recorded tracks)

Some improvements for #719

---

src/main/java/de/dennisguse/opentracks/TrackDeleteActivity.java

Thread starts on onCreate (once).
Activity's onStart checks if thread was terminated and activity finishes in that case.
Activity's onStop interrupts the thread.
All this avoids crashing when activity restarts while thread is deleting.
#705 

Bugfix: crash deleting when activity restarts

---

build.gradle

Reproducible build: disable PNG crunching.

---

build.gradle

Wait until AndroidStudio 4.2.X is released (currently beta6).

Build: replace JCenter with MavenCentral;

---

src/androidTest/java/de/dennisguse/opentracks/io/file/importer/ExportImportTest.java
src/androidTest/java/de/dennisguse/opentracks/io/file/importer/LegacyImportTest.java
src/androidTest/java/de/dennisguse/opentracks/stats/TrackStatisticsUpdaterTest.java
src/androidTest/java/de/dennisguse/opentracks/util/EGM2008UtilsTest.java
src/main/java/de/dennisguse/opentracks/content/TrackDataHub.java
src/main/java/de/dennisguse/opentracks/content/data/Altitude.java
src/main/java/de/dennisguse/opentracks/content/data/Marker.java
src/main/java/de/dennisguse/opentracks/content/data/TrackPoint.java
src/main/java/de/dennisguse/opentracks/content/provider/ContentProviderUtils.java
src/main/java/de/dennisguse/opentracks/fragments/StatisticsRecordingFragment.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/GPXTrackExporter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/AbstractFileTrackImporter.java
src/main/java/de/dennisguse/opentracks/stats/TrackStatisticsUpdater.java
src/main/java/de/dennisguse/opentracks/util/EGM2008Utils.java
src/main/res/layout/about.xml
src/main/res/layout/statistics_recording.xml
src/main/res/values/do_not_translate.xml
src/main/res/values/strings.xml

PS: EGM2008 lookup is cached, but happens currently in the UI thread.
For now that is okay, but is not cool.
Lookup should only happens once per track at a 5' minute resolution.
Adds about ~~20MB~~ 16MB as data to the APK.
More infos: https://geographiclib.sourceforge.io/html/geoid.html

Added EGM2008 undulation data.

---

src/androidTest/java/de/dennisguse/opentracks/content/data/TrackPointTest.java
src/androidTest/java/de/dennisguse/opentracks/content/sensor/SensorDataCyclingTest.java
src/androidTest/java/de/dennisguse/opentracks/stats/TrackStatisticsUpdaterTest.java
src/main/java/de/dennisguse/opentracks/content/data/Distance.java
src/main/java/de/dennisguse/opentracks/content/sensor/SensorDataCycling.java
src/main/java/de/dennisguse/opentracks/services/sensors/BluetoothRemoteSensorManager.java
src/main/java/de/dennisguse/opentracks/stats/TrackStatisticsUpdater.java
src/main/java/de/dennisguse/opentracks/util/PreferencesUtils.java

While using a cycling speed and distance sensor, the updater was not using the distance from the most recent trackpoint but rather the one considered last moving.
Fixes #762.
Added test.

Bugfix: TrackStatisticsUpdater was computing distance incorrectly.

---

src/debug/AndroidManifest.xml
src/main/AndroidManifest.xml

Should fix #685 and #129.
`hasFragileUserData=true` allows user to uninstall OpenTracks without deleting the app-internal data (actually the user can choose).
__Problem 1:__ Seemingly `hasFragileUserData=true` prevents uninstalling OpenTracks (best guess: some bugs in older Android variants).
__Problem 2:__ Anyhow: `hasFragileUserData=true` is actually an anti-feature from a privacy perspective.
It is likely that a user uninstalled OpenTracks without deleting the app-internal data.
So, the data might stay on the device and the user might not be aware of it (and that is an issue).
I even don't know if the data can be removed without wiping the device or installing OpenTracks again (and the uninstalling again).
Side note: for testing it is actually quite nice to have …

Disable hasFragileUserData for production.

---

src/main/java/de/dennisguse/opentracks/MarkerListActivity.java
src/main/java/de/dennisguse/opentracks/TrackListActivity.java
src/main/java/de/dennisguse/opentracks/util/ActivityUtils.java
src/main/res/menu/track_list.xml

Fixes #757.
Search can be used if on search start, the menu item is upgraded to an Action (i.e., `searchMenuItem.setShowAsAction(MenuItem.SHOW_AS_ACTION_ALWAYS);`).
Also simplify search setup.

TrackListActivity: re-enable search.

---

README_TESTED_SENSORS.md

Adds Rotor 2INpower powermeter to the list of tested sensors. I tested one myself

doc: add Rotor 2INpower cycling powermeter

---

src/androidTest/java/de/dennisguse/opentracks/EspressoDeleteTrackTest.java
src/androidTest/java/de/dennisguse/opentracks/content/data/TestDataUtil.java
src/androidTest/java/de/dennisguse/opentracks/util/AnnouncementUtilsTest.java
src/androidTest/java/de/dennisguse/opentracks/viewmodels/IntervalStatisticsTest.java
src/main/java/de/dennisguse/opentracks/TrackRecordedActivity.java
src/main/java/de/dennisguse/opentracks/TrackRecordingActivity.java
src/main/java/de/dennisguse/opentracks/adapters/IntervalStatisticsAdapter.java
src/main/java/de/dennisguse/opentracks/content/provider/ContentProviderUtils.java
src/main/java/de/dennisguse/opentracks/fragments/IntervalsFragment.java
src/main/java/de/dennisguse/opentracks/services/tasks/AnnouncementPeriodicTask.java
src/main/java/de/dennisguse/opentracks/viewmodels/IntervalStatistics.java
src/main/java/de/dennisguse/opentracks/viewmodels/IntervalStatisticsModel.java

**TrackStatisticsUpdater to compute Intervals**
#703 is fixed in this PR.
**Performance improvement**
- When recording every time a new track point were gotten the intervals were created. So intervals were built again and again. Now, intervals add new track points to complete them.
- Related to the above TrackDataHub have been removed from IntervalsFragment. With TrackDataHub every time the fragment was resumed all TrackPoints were sent to the ViewModel but ViewModel.
**Work to be done after this PR**
- Improve announcement performance (last interval).
- Review ChartFragment (maybe the same issue that with the IntervalsFragment).
**Why draft PR**
Because I want to test them in a long route (next weekend). But this can be already reviewed.
#703 
#808 
**License …

Intervals: performance improvement and TrackStatisticsUpdater to compute them

---

src/main/java/de/dennisguse/opentracks/fragments/IntervalsFragment.java

I overlook a tiny thing in the last intervals commit fixed here.
Also, I stumble upon strange thing checking Espresso tests: onPause viewModel can be null but I don't understand because in the onResume method viewModel is initialized. Anyway, I've added a null checking here.

Two simple bugfixes

---

src/main/res/values-de/strings.xml

It's Geschwindigkeit, not Geshwindigkeit.

Fix typo in German translation

---

src/main/java/de/dennisguse/opentracks/AbstractTrackDeleteActivity.java
src/main/res/values/strings.xml

**The problem**
#847 is a race condition because while is stopping the recording track is deleting it. Meanwhile post-export track is launching too.
I could reproduce it with some smartphones/emulators but not in others.
**My proposal**
I think the best option here is not delete the recording track but shows a Toast: "The recording track cannot be deleted. Stop it first."
#847

Race condition fixed: deleting a recording track with post-execution on

---

src/main/java/de/dennisguse/opentracks/adapters/IntervalStatisticsAdapter.java
src/main/java/de/dennisguse/opentracks/viewmodels/IntervalStatistics.java

The simple solution: show dashes.
Hiding data require some communication strategy between Intervals Adapter and Interval Fragment because IntervalFragment have to hide the header and Adapter the values... Does it worth? I don't think so.
#791

Workaround for no barometric sensor: intervals shows dashes (-) for gain and loss.

---

src/androidTest/java/de/dennisguse/opentracks/content/provider/ShareContentProviderTest.java
src/androidTest/java/de/dennisguse/opentracks/io/file/importer/ExportImportTest.java
src/androidTest/java/de/dennisguse/opentracks/util/PreferencesUtilsTest.java
src/main/java/de/dennisguse/opentracks/ShowOnMapProxyActivity.java
src/main/java/de/dennisguse/opentracks/content/provider/ShareContentProvider.java
src/main/java/de/dennisguse/opentracks/io/file/TrackFileFormat.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/KMLTrackExporter.java

Before OSMDashboard existed, I added the functionality to only share a limited set of geo data with other applications (i.e., only coordinates; no timestamps; no markers; no track description).
All of this should not be necessary anymore (due to the existence OSMDashboard) - it is a privacy respecting map application.
No need to protect the user too much.
Thus, I propose to remove this.

Remove KML/KMZ lvariants

---

src/main/java/de/dennisguse/opentracks/services/handlers/LocationHandler.java

This should fix the race condition, we see in tests.
I have not seen it in real life, but it might happen on slower devices / bad timing.

Bugfix: LocationHandler should ignore locations after stopping.

---

src/androidTest/java/de/dennisguse/opentracks/EspressoCustomLayoutTest.java
src/androidTest/java/de/dennisguse/opentracks/EspressoEditTrackRecordingTest.java
src/main/java/de/dennisguse/opentracks/content/provider/ContentProviderUtils.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingManager.java

In my opinion TrackRecordingManager should only update track's statistics every time a new track point is received. Only TrackEditActivity can edit a Track data: name, description and activity type.
I've added an Espresso test that checks that track's name is properly edited.
#916 

TrackRecordingManager only updates track's statistics

---

.github/workflows/lint.yml
.github/workflows/test.yml

The AdoptOpenJDK has been discontinued since July 2021. When using Zulu OpenJDK builds gets you all the latest and greatest (TCK Tested) builds for all versions of OpenJDK.
https://adoptopenjdk.net 
"24th July 2021: AdoptOpenJDK is moving to the Eclipse Foundation and rebranding.
Our July 2021 and future releases will come from Adoptium.net"

Using Zulu builds of OpenJDK in GH actions

---

src/main/java/de/dennisguse/opentracks/services/TrackRecordingService.java

This PR fixes a crash on Android 12, since it explicitly requires setting either FLAG_MUTABLE or FLAG_IMMUTABLE. This requirement is documented here: https://developer.android.com/about/versions/12/behavior-changes-12#pending-intent-mutability
(Tested in an Android 12 AVD and on a Pixel 4a running Android 12)
(If available): N/A

Set FLAG_IMMUTABLE for PendingIntents

---

src/androidTest/java/de/dennisguse/opentracks/viewmodels/IntervalStatisticsTest.java
src/main/java/de/dennisguse/opentracks/viewmodels/IntervalStatistics.java

The changes explain themself.
I also changed tests so I hope this bug won't appear again.
PD/ This crash is only launch for old imported tracks where there are not loss information (when we only calculated gain but not loss).
PD1/ Special mention to @FTno who discovered it.

Intervals crashed when gain != null and loss == null

---

src/main/java/de/dennisguse/opentracks/viewmodels/StatisticDataBuilder.java
src/main/res/values-b+es+419/strings.xml
src/main/res/values-cs/strings.xml
src/main/res/values-es/strings.xml
src/main/res/values-fr/strings.xml
src/main/res/values-gl/strings.xml
src/main/res/values-nb/strings.xml
src/main/res/values-pt-rBR/strings.xml
src/main/res/values-vi/strings.xml
src/main/res/values/strings.xml

While working on the sensor stuff, I noticed that for speed, we put "Sensor: " in front of the name while for the other sensors, we don't do this.

UI: Remove "Sensor:" prefix from speed description.

---

.github/workflows/build_nightly.yml
build.gradle

I'm experimenting with my own fdroid repository: https://fdroid.storchp.de/fdroid/repo
Currently it's all manually build and an apk only repository. But one can add it to the F-Droid client and would receive updates for nightlies. This needs to be automated and metadata be added.
What we also need is a nightly distinct versionCode and apk name. That's the reason for this PullRequest. I set the versionCode to the current date in the format YYYYMMDD and the apk filename to applicationId + _ + versionCode.
Probably the GitHub action need to be adjusted as well.
For #952 
@dennisguse what do you think?

Set distinct versionCode and name for nightlies

---

src/androidTest/java/de/dennisguse/opentracks/util/BluetoothUtilsTest.java
src/main/java/de/dennisguse/opentracks/util/BluetoothUtils.java

End of cycling season and I started running again using a shoe-based running sensor.
... and reported distance got negative happened 2 or 3 times.
And today, I checked the parsing code and is an overflow that happened every 6.5km (UINT16 in decimeter).
But it should be a UINT32 :/

Bugfix: running sensor data total is distance is UINT_32.

---

src/androidTest/java/de/dennisguse/opentracks/util/BluetoothUtilsTest.java
src/main/java/de/dennisguse/opentracks/util/BluetoothUtils.java

The implementation for the parsing of wheel rotation and crank rotation was weirdly implemented.
And the workarounds for Garmin Speed Sensor 2 and Wahoo CADENCE (both only measure one thing, but send the other).
https://www.bluetooth.com/wp-content/uploads/Sitecore-Media-Library/Gatt/Xml/Characteristics/org.bluetooth.characteristic.csc_measurement.xml
Not yet tested - but should be working :)

BLE cycling parsing was weirdly implemented (by me)xz

---

build.gradle

As suggested in https://github.com/OpenTracksApp/opentracksapp.github.io/pull/8#issuecomment-974642302
When this change gets merged, user who already use the nightlies from the repo need to uninstall once manually because the old versionCode scheme has a much higher number. Otherwise one would never see updates. But I guess we can communicate that, right?

Change versionCode for nightlies to commit count

---

src/main/java/de/dennisguse/opentracks/content/provider/ShareContentProvider.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/ExportService.java
src/main/java/de/dennisguse/opentracks/io/file/importer/DirectoryChooserActivity.java
src/main/java/de/dennisguse/opentracks/util/ExportUtils.java
src/main/java/de/dennisguse/opentracks/util/FileUtils.java
src/main/java/de/dennisguse/opentracks/util/IntentUtils.java

I found a few things to tackle the export to Nextcloud error.
One thing was that Nextclound can't handle `:` character in filename, so I need to strip them from the trackname before creating the file.
Then I found a few things with the flags and handling of cases where the directory uri might not be writable.
This is just a quick hack, not tested well. Please feel free to have a look anyway.

for #1025 exportdir failed to create document

---

src/main/java/de/dennisguse/opentracks/AggregatedStatisticsActivity.java
src/main/java/de/dennisguse/opentracks/TrackListActivity.java
src/main/java/de/dennisguse/opentracks/content/provider/ContentProviderUtils.java
src/main/java/de/dennisguse/opentracks/viewmodels/AggregatedStatisticsModel.java
src/main/res/menu/list_context_menu.xml

Aggregated stats has been extended to see aggregated stats only for tracks selected in the contextual menu from TrackListActivity.
Users that select tracks (open contextual menu) can see now a new item menu called "Aggregated Stats".
AggregatedStatisticsActivity expect an optional list of Track.Id and show only aggregated stats from those Track.Ids. If this list is empty or not exists then it shows aggregated stats from all tracks.
It partially fixes #1039 (see comment: https://github.com/OpenTracksApp/OpenTracks/issues/1039#issuecomment-985834549)
#1039

Aggregated stats for only selected tracks.

---

src/main/java/de/dennisguse/opentracks/io/file/importer/DirectoryChooserActivity.java
src/main/java/de/dennisguse/opentracks/util/IntentUtils.java

I was wondering why the export directory vanishes. I found a mistake in persisting the uri permission.
I also fixed the TODO comment to implement the release of the uri permission in case the directory chooser is canceled or a new directory is chosen.

fix persistable directory permissions

---

src/main/java/de/dennisguse/opentracks/settings/PreferencesUtils.java

Using a generic lookup prevents compiler optimization.
... and the code was too hard for me figure out :)
Saw this while looking into the stacktrace from #1052.

Cleanup: reference resources manually.

---

.idea/misc.xml
drawable-svg/ic_clear_filter.svg
src/androidTest/java/de/dennisguse/opentracks/EspressoAggregatedFilterTest.java
src/androidTest/java/de/dennisguse/opentracks/content/data/TrackSelectionTest.java
src/main/java/de/dennisguse/opentracks/AggregatedStatisticsActivity.java
src/main/java/de/dennisguse/opentracks/adapters/AggregatedStatisticsAdapter.java
src/main/java/de/dennisguse/opentracks/content/data/TrackSelection.java
src/main/java/de/dennisguse/opentracks/content/provider/ContentProviderUtils.java
src/main/java/de/dennisguse/opentracks/content/provider/SelectionData.java
src/main/java/de/dennisguse/opentracks/fragments/FilterDialogFragment.java
src/main/java/de/dennisguse/opentracks/util/StringUtils.java
src/main/java/de/dennisguse/opentracks/viewmodels/AggregatedStatisticsModel.java
src/main/res/drawable/ic_baseline_date_range_24.xml
src/main/res/drawable/ic_baseline_filter_alt_24.xml
src/main/res/drawable/ic_clear_filter_24dp.xml
src/main/res/layout/aggregated_stats.xml
src/main/res/layout/fragment_filter_dialog.xml
src/main/res/layout/fragment_filter_dialog_item.xml
src/main/res/menu/aggregated_statistics.xml
src/main/res/values/strings.xml

User can filter aggregated statistics by category (sport) and/or date range:
By default:
- The current week is selected (begin and end date with first day of this week and last day of this week).
- All categories are checked.
When user set a filter then AggregatedStatisticsActivity shows "clear filter" menu option instead of "filter" option to clear filters applied.
**Developers information**
FilterDialogFragment has been developed to be reused in other parts of OpenTracks if needed.
I've created an interface inside `ContentProviderUtils` called `ContentProviderSelectionInterface` that can be used to create selections from out of this class. Useful here for `Track` class to filter tracks and useful for other similar situations. In that way, …

Filter option in Aggregated Stats

---

README.md
src/androidTest/java/de/dennisguse/opentracks/content/provider/CustomContentProviderUtilsTest.java
src/androidTest/java/de/dennisguse/opentracks/io/file/importer/ExportImportTest.java
src/androidTest/java/de/dennisguse/opentracks/services/TrackRecordingServiceTest.java
src/androidTest/java/de/dennisguse/opentracks/services/TrackRecordingServiceTestLocation.java
src/androidTest/java/de/dennisguse/opentracks/services/TrackRecordingServiceTestLooper.java
src/androidTest/java/de/dennisguse/opentracks/services/TrackRecordingServiceTestStatistics.java
src/androidTest/java/de/dennisguse/opentracks/services/handlers/GPSHandlerTest.java
src/androidTest/java/de/dennisguse/opentracks/services/handlers/TrackPointCreatorTest.java
src/main/java/de/dennisguse/opentracks/content/data/TrackPoint.java
src/main/java/de/dennisguse/opentracks/content/data/TrackPointsColumns.java
src/main/java/de/dennisguse/opentracks/content/provider/CustomSQLiteOpenHelper.java
src/main/java/de/dennisguse/opentracks/fragments/IntervalsFragment.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/GPXTrackExporter.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/KMLTrackExporter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/GpxTrackImporter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/KmlTrackImporter.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingManager.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingService.java
src/main/java/de/dennisguse/opentracks/services/handlers/GPSHandler.java
src/main/java/de/dennisguse/opentracks/services/handlers/TrackPointCreator.java
src/main/java/de/dennisguse/opentracks/services/sensors/AltitudeSumManager.java
src/main/java/de/dennisguse/opentracks/stats/TrackStatistics.java

OpenTracks now tries to create TrackPoints from BLE sensors (i.e., the ones that provide distance) every second.
It is a really naive implementation and works nicely if GPS is **not** used.
The current implementation has a preference of sensor-based TrackPoints as those will be triggered more often.
This will very likely result in ignoring useful GPS locations (which are expansive to get from an energy perspective).
For this, we need some more magic (aka don't try to store sensor data every second).
Fixed #500.

Storing data without GPS

---

src/androidTest/java/de/dennisguse/opentracks/io/file/exporter/KmlTrackExporterTest.java
src/androidTest/java/de/dennisguse/opentracks/io/file/importer/ExportImportTest.java
src/androidTest/java/de/dennisguse/opentracks/util/StringUtilsTest.java
src/main/java/de/dennisguse/opentracks/content/data/Track.java
src/main/java/de/dennisguse/opentracks/content/data/TracksColumns.java
src/main/java/de/dennisguse/opentracks/content/provider/ContentProviderUtils.java
src/main/java/de/dennisguse/opentracks/content/provider/CustomSQLiteOpenHelper.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/GPXTrackExporter.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/KMLTrackExporter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/GpxTrackImporter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/KmlTrackImporter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/ParsingException.java
src/main/java/de/dennisguse/opentracks/io/file/importer/TrackImporter.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingManager.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingService.java
src/main/java/de/dennisguse/opentracks/util/StringUtils.java

This PR adds a time offset to the tracks; all times remain stored as Instant (i.e., UTC).
Data migration: existing Track will use current time offset of the phone.
Import: use the time offset from the KML/GPX
Note: time offset is stored in seconds and denotes the difference from UTC.
Note: PR is based upon #1033.
Fixes #301.

Store timezone offset when starting a recording

---

src/main/java/de/dennisguse/opentracks/settings/BluetoothLeAdapter.java
src/main/java/de/dennisguse/opentracks/settings/PreferencesUtils.java
src/main/java/de/dennisguse/opentracks/settings/bluetooth/BluetoothLeSensorPreference.java
src/main/res/values/settings.xml
src/main/res/values/strings.xml
src/main/res/xml/settings_sensors.xml

Fixes #1000.
Some devices do not announce supported service in their discovery package and this prevents users to use those with OpenTracks.
Affected devices are usually smartwatches that can measure heart rate.

Settings: add option to disable filter of BLE sensors.

---

src/androidTest/java/de/dennisguse/opentracks/chart/ChartPointTest.java
src/main/java/de/dennisguse/opentracks/chart/ChartPoint.java
src/main/java/de/dennisguse/opentracks/chart/ChartView.java
src/main/java/de/dennisguse/opentracks/content/TrackDataListener.java
src/main/java/de/dennisguse/opentracks/content/data/Altitude.java
src/main/java/de/dennisguse/opentracks/fragments/ChartFragment.java
src/main/java/de/dennisguse/opentracks/stats/AltitudeRingBuffer.java
src/main/java/de/dennisguse/opentracks/stats/RingBuffer.java
src/main/java/de/dennisguse/opentracks/stats/SpeedRingBuffer.java
src/main/java/de/dennisguse/opentracks/stats/TrackStatistics.java
src/main/java/de/dennisguse/opentracks/stats/TrackStatisticsUpdater.java

Considering altitude and speed as optional (i.e., null vs 0), enables the charts to scale the y-axis according to the min/max value instead of 0/max.
This is nice on higher altitudes.

For charts: consider altitude and speed of being optional

---

src/main/java/de/dennisguse/opentracks/io/file/importer/DirectoryChooserActivity.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingService.java
src/main/java/de/dennisguse/opentracks/settings/ImportExportSettingsFragment.java
src/main/java/de/dennisguse/opentracks/settings/PreferencesUtils.java
src/main/java/de/dennisguse/opentracks/util/ExportUtils.java
src/main/java/de/dennisguse/opentracks/util/IntentUtils.java
src/main/res/values/strings.xml

I'm still having problems with a nextcloud export directory. Sometimes (after new install of a nightly), the directory vanishes. Vanishes as in the settings activity doesn't show anything, even not "not set". So I changed the display of the name to the uri and added an indicator if it is writable.
I also added a check if the post-workout export is enabled, but the directory is null or not writable. 
Additionally I only release the uri permission, if the new selected directory is different to the previous one.

Try to takkle down export dir issues

---

src/androidTest/java/de/dennisguse/opentracks/content/DescriptionGeneratorTest.java
src/androidTest/java/de/dennisguse/opentracks/util/StringUtilsTest.java
src/androidTest/java/de/dennisguse/opentracks/util/TrackNameUtilsTest.java
src/main/java/de/dennisguse/opentracks/MarkerListActivity.java
src/main/java/de/dennisguse/opentracks/TrackListActivity.java
src/main/java/de/dennisguse/opentracks/adapters/MarkerResourceCursorAdapter.java
src/main/java/de/dennisguse/opentracks/content/DescriptionGenerator.java
src/main/java/de/dennisguse/opentracks/fragments/FilterDialogFragment.java
src/main/java/de/dennisguse/opentracks/fragments/StatisticsRecordedFragment.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingManager.java
src/main/java/de/dennisguse/opentracks/util/ListItemUtils.java
src/main/java/de/dennisguse/opentracks/util/StringUtils.java
src/main/java/de/dennisguse/opentracks/util/TrackNameUtils.java
src/main/res/values/strings.xml

- Date and time handled by OffsetDateTime Java class.
- Track default name with offset (for date local and ISO 8601 options).
- TrackListActivity: shows relative today's date (like Today, Yesterday, 22 Dec, 22 Dec 2021, etc).
- StatisticsRecordedFragment: always shows the original date and time. For example, if you record an activity at 20h then it always will show 20h regardless the zone are where you are.
- Added new tests.
**Markers**
I couldn't do anything on Markers because there is not offset in Markers table.
#301

Proper handling of timezone data on UI

---

src/androidTest/java/de/dennisguse/opentracks/io/file/importer/ExportImportTest.java
src/androidTest/java/de/dennisguse/opentracks/services/TrackRecordingServiceTestRecording.java
src/main/java/de/dennisguse/opentracks/content/data/TrackPoint.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingManager.java

A GPS-based TrackPoint that contained distance sensor data might be ignored depending on the recording distance interval.
Assumption: The actual distance should be computed against the previous GPS-based TrackPoint.
Until now, we would just ignore some of those GPS-based TrackPoints, but they costs a lot of energy to acquire, so why not store them?

Recording GPS-based TrackPoints optimization (BLE sensor only)

---

src/main/java/de/dennisguse/opentracks/services/handlers/MonotonicClock.java
src/main/java/de/dennisguse/opentracks/services/handlers/TrackPointCreator.java
src/main/java/de/dennisguse/opentracks/stats/TrackStatistics.java

`System.currentTimeMillis()` is not monotonic and might jump forward/backward whenever the local device time is updated.
This results in crashes while recording:
1. if the time jumps before start of a current segment
2. if the time jumps before the time of the previous trackpoint
Exceptions are nowadays created in TrackStatistics to prevent invalid data, leading to crashes.
We now use a clock that is relative to it's creation while using the time since boot of the device (guaranteed to be monotonic).
https://developer.android.com/reference/android/os/SystemClock
Fixes #800.

Bugfix: use monotonic clock.

---

src/main/java/de/dennisguse/opentracks/io/file/importer/DirectoryChooserActivity.java
src/main/java/de/dennisguse/opentracks/settings/ImportExportSettingsFragment.java
src/main/java/de/dennisguse/opentracks/settings/PreferencesUtils.java
src/main/java/de/dennisguse/opentracks/util/ExportUtils.java
src/main/java/de/dennisguse/opentracks/util/IntentUtils.java
src/main/res/values/strings.xml

The Uris from Intent.getData() and DocumentFile.getUri() seems to be different. I think PreferencesUtils should only work with the original Uri as well as the permission handling logic.
IntentUtils.toDocumentFile can be used to convert it to a DocumentFile later on to actually work with.
Adds "No file manager found" message if no activity with OPEN_DOCUMENT_TREE is found. #1095
Removed deprecation of `startActivityForResult`.
I'm not sure if `IntentUtils.toDocumentFile(getContext(), directoryUri);` is at the right place. Maybe `FileUtils` is a better place.
This PR improves the situation a bit, but still doesn't solve the lost write permission on the next cloud folders. I'm still investigating.

Change handling of Uri and DocumentFile for #1080 and #1095

---

README.md
src/main/AndroidManifest.xml
src/main/java/de/dennisguse/opentracks/publicapi/AbstractAPIActivity.java
src/main/java/de/dennisguse/opentracks/publicapi/StartRecording.java
src/main/java/de/dennisguse/opentracks/publicapi/StopRecording.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingService.java
src/main/java/de/dennisguse/opentracks/settings/PreferencesUtils.java
src/main/res/values/settings.xml
src/main/res/values/strings.xml
src/main/res/xml/settings.xml

Public API: enable other applications to start recordings.

---

src/androidTest/java/de/dennisguse/opentracks/util/FileUtilsTest.java
src/main/java/de/dennisguse/opentracks/util/FileUtils.java

Fixes #1129.
This PR has the side affect that only ASCII characters can be used for filenames.
Before that all UTF characters > 127 could be used - I just don't know why somebody would want this.

Bugfix: emojis cannot be used as filenames.

---

src/main/java/de/dennisguse/opentracks/io/file/exporter/ExportServiceResultReceiver.java
src/main/java/de/dennisguse/opentracks/io/file/importer/DirectoryChooserActivity.java
src/main/java/de/dennisguse/opentracks/util/IntentUtils.java

Still not sure why the persisted URI permission gets lost, but I saw that we use different contexts to persist the URI and to get the DocumentFile from it. Let's use ApplicationContext everywhere because sometimes it's an Activity and sometimes a Service.
Also stumbled upon a RuntimeException after exporting because missing breaks in a switch statement.

for #1080: maybe the different type of Contexts are the problem

---

src/androidTest/java/de/dennisguse/opentracks/content/data/TestDataUtil.java
src/androidTest/java/de/dennisguse/opentracks/services/announcement/VoiceAnnouncementUtilsTest.java
src/androidTest/java/de/dennisguse/opentracks/stats/TrackStatisticsTest.java
src/androidTest/java/de/dennisguse/opentracks/stats/TrackStatisticsUpdaterTest.java
src/main/java/de/dennisguse/opentracks/services/announcement/VoiceAnnouncement.java
src/main/java/de/dennisguse/opentracks/services/announcement/VoiceAnnouncementUtils.java
src/main/java/de/dennisguse/opentracks/settings/PreferencesUtils.java
src/main/java/de/dennisguse/opentracks/stats/TrackStatistics.java
src/main/java/de/dennisguse/opentracks/stats/TrackStatisticsUpdater.java
src/main/java/de/dennisguse/opentracks/ui/intervals/IntervalStatistics.java
src/main/res/values/settings.xml
src/main/res/values/strings.xml
src/main/res/xml/settings_announcements.xml

This PR adds a new option to announce heart rate info in voice announcements. It defaults to false to preserve current behavior.
I was unable to run the tests locally because Espresso kept crashing so I'm hoping GitHub will run them for me. There is one test that will fail (there is a TODO comment). But I wanted to submit the PR to get some feedback on the approach and overall desirability of the feature at all.
No issue. I just went ahead and built it because I wanted it.
[EDIT] I also implemented TtsSpans to make it easier to understand the spoken numbers.
https://github.com/OpenTracksApp/OpenTracks/issues/876
By opening this pull request, you are providing your contribution under the _Apache License 2.0_ (see …

Voice heart rate

---

README_TESTED_SENSORS.md

Cadence is a bit of an unknown.  OpenTracks sees the Tickr X as being able to provide
cadence but doesn't display anything for it while walking on the treadmill, for example.
The Wahoo Fitness app does show cadence from the Tickr X while walking on the
treadmill.

Add information about Wahoo Tickr X

---

src/androidTest/java/de/dennisguse/opentracks/io/file/importer/ExportImportTest.java
src/androidTest/java/de/dennisguse/opentracks/services/TrackRecordingServiceTestRecording.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingManager.java

Fixes #1059.
A valid LastTrackPoint (with distance) is not stored if it did not met the recording distance requirement and no change idle/non-idle took place.
@vlmendz @niekto350 could you test this?

Adhere to recording distance interval for TrackPoint storage.

---

.gitignore
src/androidTest/java/de/dennisguse/opentracks/io/file/TrackFilenameGeneratorTest.java
src/androidTest/java/de/dennisguse/opentracks/io/file/TrackFilenameGeneratorTest2.java
src/main/java/de/dennisguse/opentracks/io/file/TrackFilenameGenerator.java
src/main/java/de/dennisguse/opentracks/settings/ImportExportSettingsFragment.java
src/main/java/de/dennisguse/opentracks/settings/PreferencesUtils.java
src/main/java/de/dennisguse/opentracks/share/ShareUtils.java
src/main/java/de/dennisguse/opentracks/util/ExportUtils.java
src/main/res/values/settings.xml
src/main/res/values/strings.xml
src/main/res/xml/settings_import_export.xml

Used for all automatic exports after recording, exporting all, and sharing tracks.
Ready for testing.
Also changes default fileformat to: `time_name.suffix`
Configuration option is in the settings under Import/Export.
Fixes #512.

Configurable filename for export.

---

README.md
src/main/AndroidManifest.xml
src/main/java/de/dennisguse/opentracks/TrackListActivity.java
src/main/java/de/dennisguse/opentracks/TrackRecordedActivity.java
src/main/java/de/dennisguse/opentracks/TrackRecordingActivity.java
src/main/java/de/dennisguse/opentracks/fragments/StatisticsRecordingFragment.java
src/main/java/de/dennisguse/opentracks/publicapi/AbstractAPIActivity.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingServiceConnection.java
src/main/java/de/dennisguse/opentracks/settings/MainSettingsFragment.java
src/main/java/de/dennisguse/opentracks/ui/markers/MarkerListActivity.java

The stop intent is now handled properly.
This is achieved by extracting starting the recording from `TrackRecordingActivity` into the calling code.
`TrackRecordingActivity` finishes automatically if the recording is stopped. 
Beforehand `TrackRecordingActivity` was starting the recording if the `TrackRecordingService` was not recording.
However, this restarted recording if stopped via Intent if `TrackRecordingActivity` was brought into foreground.
Build on top of #1155.
TODO:

Implement Public API stop

---

src/androidTest/java/de/dennisguse/opentracks/io/file/importer/ExportImportTest.java
src/androidTest/java/de/dennisguse/opentracks/services/TrackRecordingServiceTestUtils.java
src/androidTest/java/de/dennisguse/opentracks/services/handlers/TrackPointCreatorTest.java
src/main/java/de/dennisguse/opentracks/sensors/BluetoothConnectionManager.java
src/main/java/de/dennisguse/opentracks/sensors/BluetoothRemoteSensorManager.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingService.java
src/main/java/de/dennisguse/opentracks/services/handlers/TrackPointCreator.java

Otherwise the thread is not defined and a SecurityException may be triggered when inserting data into the ContentProvider.
Part of #1165.
BUT we can only deploy this actual fix for API>26.
All others may always/often/sometimes/never be able to store BLE sensor provided data (without GPS).
```
/home/runner/work/OpenTracks/OpenTracks/src/main/java/de/dennisguse/opentracks/sensors/BluetoothConnectionManager.java:132: Error: Call requires API level 26 (current min is 21): android.bluetooth.BluetoothDevice#connectGatt [NewApi]
bluetoothGatt = device.connectGatt(context, true, connectCallback, BluetoothDevice.TRANSPORT_AUTO, 0, this.observer.getHandler());
```

Bluetooth: use TrackRecording handler for callback.

---

src/main/java/de/dennisguse/opentracks/io/file/exporter/CSVTrackExporter.java

I thought it was EXCEL or the csv-to-xlsx-converter, until I realized, the data is also broken in newly generated csv files.
Should fix csv exports, so they contain latitude AND longitude instead of latitude twice.
I've not looked in the issues, I just put "csv latitude" into the searchbar, found two files of this repo, looked at the one which has not "Test" in it's name, searched for "latitude" there and found three hits in two lines and changed one of them into a naming, that seems legit to me. I'm not a java-Dev and also not really into this project, I don't even know how to compile/run/test it.
It's ok to put my contribution under the _Apache License 2.0_ (see [LICENSE.md](LICENSE.md)).
**Note: new …

Changed second t.getLatitude() to t.getLongitude()

---

src/main/java/de/dennisguse/opentracks/TrackRecordingActivity.java
src/main/java/de/dennisguse/opentracks/sensors/BluetoothRemoteSensorManager.java
src/main/java/de/dennisguse/opentracks/settings/bluetooth/BluetoothLeSensorPreference.java
src/main/java/de/dennisguse/opentracks/util/PermissionUtils.java

We now request GPS and Bluetooth on application startup aka in TrackListActivity.
Before that the GPS permission were requested in TrackRecordingActivity as this activity was actually starting the recording.
As TrackListActivity now starts the recording, the permissions would be then requested too late.
Now we request both at startup.
... but we request permissions that we do not yet need.
In addition, the Bluetooth permissions (Android 12+) were requested in the settings only (now also on startup).
To be considered: Public API does not request permissions.
Do we need this?
Implementing #240 would enable us to request permissions before actually starting the recording?
Permissions can only be requested in activities.

Refactor permission requests.

---

src/main/res/layout/track_edit_fields.xml

When naming activities, I always have to manually disable capitalization for every new word, which alters my experience of entering text. I think it is more natural to capitalize sentences only. Maybe you could even envision adding a setting that would enable the user to choose between word or sentence-only capitalization.
I am providing my contribution under the _Apache License 2.0_ (see [LICENSE.md](LICENSE.md)).

Change track title capitalization to sentences

---

src/main/java/de/dennisguse/opentracks/ui/intervals/IntervalsFragment.java

For imperial setting, intervals dropdown did show metrics values instead of imperial ones.
#1288

Bugfixed: DistanceFormatter was using the wrong unitSystem. Fixes #1288.

---

src/androidTest/java/de/dennisguse/opentracks/services/announcement/VoiceAnnouncementUtilsTest.java
src/main/java/de/dennisguse/opentracks/services/announcement/VoiceAnnouncementUtils.java

We extracted integral parts before rounding, but String.format does
rounding which caused occasional issues. This fixes that by rounding all
values as we fetch them, so the String.format rounding won't break
anything.
Fixes: #1285

Fix voice announcement rounding problem

---

.github/workflows/build_apk.yml

Somehow, it confused me (especially when telling other people how to test) that we have an F-Droid nightly and then this Github action APK.
So, my proposal: rename the build job.
Potential follow-up: use a different package name.

Github actions: rename APK build job.

---

src/androidTest/java/de/dennisguse/opentracks/io/file/importer/ExportImportTest.java
src/androidTest/java/de/dennisguse/opentracks/services/TrackRecordingServiceTestRecording.java
src/main/java/de/dennisguse/opentracks/data/models/TrackPoint.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingManager.java

Stores sensor-only data like heartrate without requiring GPS/distance data.
Allows to train indoor and still collect heartrate or powemeter over time.
Fixes #1088.
Note: not yet tested.

Store sensor-only data (without distance)

---

build.gradle
src/releasePlayStore/res/drawable-v26/ic_launcher.xml
src/releasePlayStore/res/drawable/ic_launcher.xml
src/releasePlayStore/res/values-v26/ic_launcher_background.xml

Part of #1329.
If I didn't do anything completely wrong, buildTypes only allow us to modify _some_ resources (like app_icon).
So, to replace the internally used app_icon, we would need to use buildFlavors as well.
https://developer.android.com/studio/build/build-variants#groovy

PlayStore: use an inverted icon (app launcher only).

---

src/androidTest/java/de/dennisguse/opentracks/services/announcement/VoiceAnnouncementUtilsTest.java
src/main/java/de/dennisguse/opentracks/services/announcement/VoiceAnnouncementUtils.java
src/main/res/values/strings.xml

And report distance only with one decimal unit.
Fixes #1346.

Voice announcements: "speed" -> "average moving speed" (en only).

---

README.md
src/androidTest/java/de/dennisguse/opentracks/io/file/exporter/KmlTrackExporterTest.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/KMLTrackExporter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/KmlTrackImporter.java

Export format is now KML2.3.
The importer supports KML2.2 and KML2.3.
Tested with:

Upgrade to KML2.3

---

src/main/java/de/dennisguse/opentracks/services/handlers/GPSHandler.java

Fixes #1380
Just a simple check to avoid a crash. The user won't get notified though. I'm just assuming the user knows that their device doesn't have this feature.
API level 31 (Android 12) has the nicer method [hasProvider()](https://developer.android.com/reference/android/location/LocationManager#hasProvider(java.lang.String)), but my check does basically the same.

Check if the device has GPS

---

gradle.properties
src/androidTest/java/de/dennisguse/opentracks/services/announcement/VoiceAnnouncementUtilsTest.java
src/androidTest/java/de/dennisguse/opentracks/ui/aggregatedStatistics/EspressoAggregatedFilterTest.java
src/main/java/de/dennisguse/opentracks/TrackListActivity.java
src/main/java/de/dennisguse/opentracks/data/CustomContentProvider.java
src/main/java/de/dennisguse/opentracks/io/file/importer/TrackImporter.java
src/main/java/de/dennisguse/opentracks/services/TrackDeleteService.java
src/main/res/drawable/ic_baseline_delete_24.xml
src/main/res/values-b+es+419/strings.xml
src/main/res/values-cs/strings.xml
src/main/res/values-de/strings.xml
src/main/res/values-es/strings.xml
src/main/res/values-fr/strings.xml
src/main/res/values-gl/strings.xml
src/main/res/values-nb/strings.xml
src/main/res/values-nl/strings.xml
src/main/res/values-pt-rBR/strings.xml
src/main/res/values-ru/strings.xml
src/main/res/values-tr/strings.xml
src/main/res/values-vi/strings.xml
src/main/res/values-zh/strings.xml
src/main/res/values/strings.xml

... before it was 2 decimal units.
Leading situations like `5.01 km` or `10.02 km`.
The 2nd decimal unit is not useful (at least not too me) and it suggests a precision that is not there.

Voice announcements: distance only with one decimal unit.

---

src/main/res/layout/help.xml
src/main/res/values/strings.xml

The question "Does OpenTracks require/use Google Play Service?" used "@android:string/no" as answer. But actually the value of this string is "Cancel". So i add new string.

Fixed bad string for an answer in the FAQ

---

.github/workflows/test.yml.disabled
src/androidTest/java/de/dennisguse/opentracks/services/handlers/GPSHandlerTest.java
src/main/java/de/dennisguse/opentracks/services/handlers/GPSHandler.java
src/main/java/de/dennisguse/opentracks/services/handlers/TrackPointCreator.java

Fixes #1328.
This should fix the race condition while shutting down TrackRecordingService and getting GPS data in parallel.

Handle LocationManager callbacks with TrackRecordingService's handler.

---

src/main/res/values-de/strings.xml

Change the German translation of the "Open Track" button label from "Offene Strecke" ("open" as an adjective) to "Strecke öffnen" ("open" as a verb).
Without context, the original english phrase is ambiguous and both variants would be correct translations, but as a button label in the context of importing a track it is clear that "open" is supposed to be a verb and the phrase is an action prompt, and not an adjective to describe the track.
_On a personal note: I've been happily using OpenTracks for about two years now to track shorter routes and display tracks from a fitness tracker. It's a really useful app to me. Thanks for all the effort! :)_

Fix incorrect German translation of "Open Track"

---

README.md

Hi,
This PR adds the opensource application [**FitTrackee**](https://github.com/SamR1/FitTrackee) to the compatibility matrix in README.  
(Note: **FitTrackee** is only compatible with GPX format and not KML/KMZ formats for now).

README: add FitTrackee to format compatibility matrix

---

src/main/AndroidManifest.xml
src/main/res/xml/backup_rules_30_lower.xml
src/main/res/xml/backup_rules_31_higher.xml

TL;DR: This PR enables the native android backup feature **only** if the backup is encrypted on the client side.
I was setting up [seedvault](https://github.com/seedvault-app/seedvault) on LineageOS when I realized that backups were not a thing on my device for OpenTracks only.
From my brief issue searching I found 2 issues, #346 and subsequently #710 I understand that this is a touchy subject.
Even if I don't completely align with the rational behind the decision to not implement this straight out of the box, I respect it.
So as @dennisguse [replied in the latter issue](https://github.com/OpenTracksApp/OpenTracks/issues/710#issuecomment-822656039), here goes a PR to try to reach a solution to which everyone can be content with.
Followed the [android …

Enable backups if client side encryption is enabled

---

src/main/java/de/dennisguse/opentracks/TrackRecordingActivity.java

Fixes #142924.
Hopefully this fixing the incorrectly popping up of the "GPS disabled"-snackbar.

Bugfix: GPS disabled warning was showing (repeatedly but incorrectly).

---

build.gradle

@elastic-rock was `resConfigs` required for Android 13's per app-language setting?
In 7dcc0ec8, I changed the behavior to use AGP  to generate the configuration.
I presume that thus resConfigs should not be necessary anymore.
Would you have time to test this?

Build: remove resConfigs limiting included languages.

---

src/androidTest/java/de/dennisguse/opentracks/services/handlers/GpsStatusTest.java
src/main/java/de/dennisguse/opentracks/services/handlers/GPSManager.java
src/main/java/de/dennisguse/opentracks/services/handlers/GpsStatus.java
src/main/java/de/dennisguse/opentracks/services/handlers/GpsStatusManager.java

Fixes #1429.
The problem occurred once the signal was lost as this triggered (ie. timeout), which triggered a stop for the timer to wait for GPS signals.
This stop event then fired a GPS disabled event... and a repetition of everything.

Bugfix: GPS disabled warning was shown repeatedly.

---

build.gradle
src/androidTest/java/de/dennisguse/opentracks/services/announcement/VoiceAnnouncementUtilsTest.java
src/main/java/de/dennisguse/opentracks/services/announcement/VoiceAnnouncementUtils.java
src/main/res/values/strings.xml

For fixing #1584 
TODO:
* ~~[ ] add lint for not using `getQuantityString()`~~  #1615
* ~~[ ] add lint for checking all ICU plural strings for proper formatting~~  #1615
NOTE: translation still need to be migrated (except for English.US).

Plural quantities

---

src/androidTest/java/de/dennisguse/opentracks/services/announcement/VoiceAnnouncementUtilsTest.java
src/main/java/de/dennisguse/opentracks/services/announcement/VoiceAnnouncementUtils.java

Fixes #1626
`IMPERIAL_METER` case was not handled in `getAnnouncement`

Bugfix: crash on voice announcement if using imperial with meters

---

src/main/java/de/dennisguse/opentracks/chart/ChartView.java

fixes #1627
I'm not entirely sure that taking `spacer` into account here is the correct approach, but it works and `spacer` is used in several other places when calculating the height / bottom.

Fix clipped x graph in ChartView

---

src/main/java/de/dennisguse/opentracks/settings/SensorsSettingsFragment.java

fixes #1637 
@dennisguse what do you think?

Bluetooth settings: handle missing permissions / avoid crash

---

build.gradle

Merge this PR, when the stable version of AGP 8.1.0 is released.
This will allow Dependabot to propose stable updates only again for this dependency.
https://mvnrepository.com/artifact/com.android.tools.build/gradle?repo=google

Bump com.android.tools.build:gradle from 8.1.0-beta04 to 8.1.0

---

src/main/res/layout/statistics_recorded.xml

This bug accidentally made it into db1a37f. Android Studio, for some reason, has made this change automatically and I didn't notice it. Sorry about that.
Without this fix, the alignment of the two columns isn't correct in landscape orientation or different screen sizes.

Fix alignment of Statistics

---

README.md
src/main/AndroidManifest.xml
src/main/java/de/dennisguse/opentracks/util/PermissionRequester.java

As discussed in https://github.com/OpenTracksApp/OpenTracks/issues/1653 , I've added the ACCESS_BACKGROUND_LOCATION and tested it successfully.
Starting to track a training while the phone is in standby now works with GPS.

Fix: GPS Access denied when device in standby

---

src/androidTest/java/de/dennisguse/opentracks/util/StatisticsUtilsTest.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/KMLTrackExporter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/KmlTrackImporter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/KmzTrackImporter.java
src/main/java/de/dennisguse/opentracks/ui/TrackListAdapter.java
src/main/java/de/dennisguse/opentracks/ui/customRecordingLayout/RecordingLayoutIO.java

This change defensively switches the order of literals in comparison expressions to ensure that no null pointer exceptions are unexpectedly thrown. Runtime exceptions especially can cause exceptional and unexpected code paths to be taken, and this can result in unexpected behavior. 
Both simple vulnerabilities (like information disclosure) and complex vulnerabilities (like business logic flaws) can take advantage of these unexpected code paths.
Our changes look something like this:
```diff
String fieldName = header.getFieldName();
String fieldValue = header.getFieldValue();
- if(fieldName.equals("requestId")) {
+ if("requestId".equals(fieldName)) {
logRequest(fieldValue);
}
```
<details>
<summary>More reading</summary>
* …

Switch order of literals to prevent NullPointerException 

---

.github/workflows/test.yml

... we have missed to adjust some test in the recent past before merging PRs.
A flacky test execution is better than no test execution.

Re-enable Github Action executes tests.

---

src/androidTest/java/de/dennisguse/opentracks/EspressoDeleteTrackTest.java
src/androidTest/java/de/dennisguse/opentracks/EspressoUITest.java

We can just find the element by matching the first child of the RecyclerView.
Tested locally, since CI has some issues right now.
`selectAndDeleteTrack` does basically a subset of `espressoDeleteTrackTest`, so it probably can be deleted without changing the test coverage.

Fix broken TrackList UI tests

---

src/main/java/de/dennisguse/opentracks/ui/TrackListAdapter.java

Fixes: #1711
The long click crash happened, because we didn't check whether we are already in selection mode.
The context menu item crash happened in `setAllSelected`, because item count != view holder count. That was a design error of me that the SparseBooleanArray uses the view holder positions, which change their contents, as the keys. So now I switched to using the trackIds, which are stored as Integers in the database, so we can easily convert them to long and back. This also simplifies the `getSelectedIds` method. The values from `getSelectedPositions` don't get used in the TrackListActivity, so we can just use null.
In regards to the [`recyclerview-selection`](https://developer.android.com/reference/androidx/recyclerview/selection/package-summary) library you mentioned, I …

TrackList: Fix crashes in selection mode

---

src/main/AndroidManifest.xml
src/main/java/de/dennisguse/opentracks/AbstractActivity.java
src/main/java/de/dennisguse/opentracks/ui/util/ActivityUtils.java

Android 13+; Predictive back for all OpenTracks's activities that don't override `onBackPressed()`.

Predictive#1708

---

doc/opentracks-schema-1.0.xsd
src/androidTest/java/de/dennisguse/opentracks/data/CustomContentProviderUtilsTest.java
src/androidTest/java/de/dennisguse/opentracks/io/file/importer/ExportImportTest.java
src/androidTest/java/de/dennisguse/opentracks/io/file/importer/GPXTrackImporterTest.java
src/androidTest/res/raw/gpx_timezone.gpx
src/main/java/de/dennisguse/opentracks/data/ContentProviderUtils.java
src/main/java/de/dennisguse/opentracks/data/CustomSQLiteOpenHelper.java
src/main/java/de/dennisguse/opentracks/data/models/ActivityIcon.java
src/main/java/de/dennisguse/opentracks/data/models/ActivityType.java
src/main/java/de/dennisguse/opentracks/data/models/Track.java
src/main/java/de/dennisguse/opentracks/data/tables/TracksColumns.java
src/main/java/de/dennisguse/opentracks/fragments/StatisticsRecordedFragment.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/ExportActivity.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/GPXTrackExporter.java
src/main/java/de/dennisguse/opentracks/io/file/exporter/KMLTrackExporter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/GpxTrackImporter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/ImportActivity.java
src/main/java/de/dennisguse/opentracks/io/file/importer/ImportViewModel.java
src/main/java/de/dennisguse/opentracks/io/file/importer/KmlTrackImporter.java
src/main/java/de/dennisguse/opentracks/io/file/importer/TrackImporter.java
src/main/java/de/dennisguse/opentracks/settings/PreferencesUtils.java
src/main/java/de/dennisguse/opentracks/settings/bluetooth/BluetoothLeSensorPreference.java
src/main/java/de/dennisguse/opentracks/ui/TrackListAdapter.java
src/main/java/de/dennisguse/opentracks/ui/customRecordingLayout/RecordingLayout.java
src/main/java/de/dennisguse/opentracks/util/ExportUtils.java

GPXs `<type>` doesn't specify if it should contain localized or non-localized (i.e., English) content, but most applications use the non-localized approach.
OpenTracks was doing the former and actually didn't store a non-localized activity type at all, but rather just the information about the icon.
What has been done:
1. Introduced `Track.activityType` in addition to `Track.activityTypeLocalized`
2. Removed ActivityIcon as the icon identifier is superseeded by ActivityType
3. Implemented database migration to determine TracksColumn.ActivityType (first using activityTypeLocalized and then icon (sadly it cannot be perfect)
4. KML now export and import activityType and activityTypeLocalized
5. KML does not export/import icon anymore
6. GPX now export `<type>` as activityType while the …

Introduced ActivityType is now non-localized (i.e., English) value

---

src/main/java/de/dennisguse/opentracks/sensors/driver/BarometerInternal.java

I experimented a little bit. I'm not sure what happens here, but I guess the internal Object Instance of the SensorEventListener doesn't "see" the null observer right away. When I implement the SensorEventListener interface directly on the BarometerInternal the NPE is fixed.

fix NPE at null barometer after unregister listener

---

src/main/java/de/dennisguse/opentracks/util/ExportUtils.java

Found the cause of the broken .gpx exports. 
As the tracks were duplicates (from test ex- and imports). The export all function wrote two times to the same file. The second time the content was slightly less bytes, so the first file was only partly overwritten resulting in a broken xml file.
We need to make sure the target file is properly overwritten (truncated at the beginning).
Solution:
https://stackoverflow.com/questions/56902845/how-to-properly-overwrite-content-of-file-using-android-storage-access-framework
@dennisguse do we have to do anything else if two tracks result in the same filename and overwriting each other while exporting?

fix #1769 export overwrite existing files

---

src/main/java/de/dennisguse/opentracks/TrackListActivity.java
src/main/java/de/dennisguse/opentracks/sensors/driver/BarometerInternal.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingService.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingServiceConnection.java

Problem(s):
* TrackListActivity started sensors and recording (always).
* The TrackRecordingService checked only if a recording was running and NOT if the sensors were already started.
Follow-up:
* Shutdown of sensors may not been correct for quite a while
* Sensor data shouldn't have been affected
Moreover: TrackListActivity's start and stop sensor didn't work correctly.

Fix crash due to BLE sensor data reported after shutdown

---

README_TESTED_SENSORS.md

OpenTracks accepts power and cadence information form this sensor but it was not in the tested list.
The sensor supports power, cadence, balance, smoothness. Only power and cadence are read by OpenTracks. Good enough.

add Magene PES P505 to the list of tested BLE cycling power sensors

---

src/main/java/de/dennisguse/opentracks/chart/ChartValueSeries.java
src/main/java/de/dennisguse/opentracks/chart/ChartView.java

titles need to take less vertical space for charts to be legible
in landscape mode when more channels (data series) are available
Fixes #1807
https://github.com/OpenTracksApp/OpenTracks/issues/1807

more compact chart titles

---

src/main/res/values/strings.xml

This fixes #1801 the most easy way. It does not implement announcer's
interval statistics over time intervals. Instead, it only clarifies
that "lap" quantities in the announcer are related to lap length.
Therefore they will not work if there is no lap length defined.
#1801

clarify that announcer's "distance interval" corresponds to "lap length"

---

src/main/java/de/dennisguse/opentracks/services/announcement/VoiceAnnouncementUtils.java

Check if total distance is a whole number to prevent TTS reading out "point zero" unnecessarily

Voice Announcements remove "point zero"

---

src/main/java/de/dennisguse/opentracks/chart/ChartValueSeries.java
src/main/java/de/dennisguse/opentracks/chart/ChartView.java

This makes charts more readable when there are many curves in it.
Side effects:
Disadvantage: chartDimensions as a new member of ChartView
Advantage: getChartDimensions called only once …

fill the area below a chart curve only when there are at most 2 curves

---

src/androidTest/java/de/dennisguse/opentracks/services/TrackRecordingServiceRecordingTest.java
src/main/java/de/dennisguse/opentracks/sensors/sensorData/Aggregator.java
src/main/java/de/dennisguse/opentracks/sensors/sensorData/AggregatorGPS.java
src/main/java/de/dennisguse/opentracks/sensors/sensorData/SensorDataSet.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingManager.java

A combination of idle trackpoint and stale GPS data, resulted in recording lat=0.0 and lng=0.0; and thus inflating distance as well as GPS-based speed.
Fixes #1898.
Introduced in dfdbc373ff90c37c8fb5fab396f3c470eee65772

Bugfix: overestimated distance.

---

src/main/java/de/dennisguse/opentracks/services/announcement/VoiceAnnouncementUtils.java
src/main/java/de/dennisguse/opentracks/settings/PreferencesUtils.java
src/main/java/de/dennisguse/opentracks/stats/TrackStatistics.java
src/main/java/de/dennisguse/opentracks/stats/TrackStatisticsUpdater.java
src/main/java/de/dennisguse/opentracks/ui/intervals/IntervalStatistics.java
src/main/res/values/strings.xml
src/main/res/xml/settings_announcements.xml

Power announcement is controlled by options. Also order of announcer options is changed so that it is more clear that "Lap" related options work only when lap is defined. All lap related options are next to each other now.
I guess you can change #1812 to a feature request now. I think it is clear enough in the options that "Lap" quantities need lap defined.
Implements #1806

support for lap cycling power in the announcer

---

src/main/res/layout/marker_list.xml
src/main/res/layout/track_list.xml

Fixes #1962
The icons in the search bar of the track-list and marker-list views are now centered.

Center icons in marker-list and track-list search bar

---

src/main/java/de/dennisguse/opentracks/ui/TrackListAdapter.java

One should react to underlying data changes if it changes, right?
Fixes #1934.
Fixes #1982.

Bugfix: Track list not updating recording status correctly.

---

src/main/java/de/dennisguse/opentracks/settings/LocalePreference.java
src/main/res/values/settings.xml
src/main/res/values/strings.xml
src/main/res/xml/settings_user_interface.xml

Corsican was not available using Android's per-app-language-chooser.
Fixes #1974.
(If available): The link to the …

Settings: add custom language/locale chooser (SDK33+).

---

src/androidTest/java/de/dennisguse/opentracks/publicapi/PublicApiTest.java
src/main/java/de/dennisguse/opentracks/publicapi/AbstractAPIActivity.java
src/main/java/de/dennisguse/opentracks/publicapi/StartRecording.java

Problem was that the TrackRecordingService was not started as a ForegroundService anymore.
Fixes #1904.

Bugfix: PublicAPI StartRecording recorded no data.

---

src/main/java/de/dennisguse/opentracks/sensors/sensorData/Aggregator.java
src/main/java/de/dennisguse/opentracks/sensors/sensorData/AggregatorBarometer.java
src/main/java/de/dennisguse/opentracks/sensors/sensorData/AggregatorGPS.java
src/main/java/de/dennisguse/opentracks/sensors/sensorData/AggregatorHeartRate.java

When becoming idle, reset the sensor data, so it is only stored once.
If after becoming idle, the sensors report new data that's fine.
Fixes #1995.

Bugfix: on idle detection reset movement-based sensor data.

---

README.md
src/androidTest/java/de/dennisguse/opentracks/data/CustomContentProviderUtilsTest.java
src/main/AndroidManifest.xml
src/main/java/de/dennisguse/opentracks/data/ContentProviderUtils.java
src/main/java/de/dennisguse/opentracks/publicapi/AbstractAPIActivity.java
src/main/java/de/dennisguse/opentracks/publicapi/CreateMarker.java
src/main/java/de/dennisguse/opentracks/publicapi/CreateMarkerActivity.java
src/main/java/de/dennisguse/opentracks/publicapi/ShowMarkerActivity.java
src/main/java/de/dennisguse/opentracks/services/TrackRecordingService.java

Public API: allow marker creation.

---

.github/workflows/build_apk.yml
build.gradle

Reproducible build: F-Droid needs build flavors (not build types).

---

src/androidTest/java/de/dennisguse/opentracks/io/file/importer/ExportImportTest.java
src/androidTest/java/de/dennisguse/opentracks/sensors/sensorData/AggregatorBarometerTest.java
src/androidTest/java/de/dennisguse/opentracks/sensors/sensorData/SensorDataCyclingTest.java
src/androidTest/java/de/dennisguse/opentracks/services/TrackRecordingServiceRecordingTest.java
src/main/java/de/dennisguse/opentracks/sensors/BluetoothHandlerBarometricPressure.java
src/main/java/de/dennisguse/opentracks/sensors/BluetoothHandlerCyclingCadence.java
src/main/java/de/dennisguse/opentracks/sensors/BluetoothHandlerCyclingDistanceSpeed.java
src/main/java/de/dennisguse/opentracks/sensors/BluetoothHandlerManagerCyclingPower.java
src/main/java/de/dennisguse/opentracks/sensors/BluetoothHandlerManagerHeartRate.java
src/main/java/de/dennisguse/opentracks/sensors/BluetoothHandlerRunningSpeedAndCadence.java
src/main/java/de/dennisguse/opentracks/sensors/SensorManager.java
src/main/java/de/dennisguse/opentracks/sensors/driver/BarometerInternal.java
src/main/java/de/dennisguse/opentracks/sensors/sensorData/Aggregator.java
src/main/java/de/dennisguse/opentracks/sensors/sensorData/Raw.java
src/main/java/de/dennisguse/opentracks/sensors/sensorData/SensorDataSet.java
src/main/java/de/dennisguse/opentracks/services/handlers/GPSManager.java
src/main/java/de/dennisguse/opentracks/services/handlers/TrackPointCreator.java
src/main/java/de/dennisguse/opentracks/viewmodels/SensorStatisticsViewHolder.java

We now use the monotonic clock everywhere. Almost everywhere.
Code is now uglier, but at least the time source is everywhere the same :D

Monotonic clock#1966

---

build.gradle

For the nightlies we need to `setVersionCodeOverride(getVersionCode())` before creating the `outputFileName = "${applicationId}_${variant.versionCode}.apk"`

fix nightly filename

---

src/main/java/de/dennisguse/opentracks/chart/ChartFragment.java
src/main/java/de/dennisguse/opentracks/chart/ChartView.java
src/main/java/de/dennisguse/opentracks/settings/PreferencesUtils.java
src/main/res/values/settings.xml
src/main/res/values/strings.xml
src/main/res/xml/settings_user_interface.xml

Adds toggles to the User Interface section of the app Settings that allow the user to display or hide the three series available in the chart: Elevation, Speed/Pace, and Heart Rate. As a user of a heart rate monitor primarily during strength workouts and combat sports, the distance and elevation graphs are not helpful to me - in addition, their scale means that I am not able to easily see my exact heart rate. This should allow users in a similar situation to better determine exactly what is most helpful for them to be seen on the graph.
- #1297 
- #2040

WIP - add settings toggles for chart series (#1297)

---

src/main/res/values-de/strings.xml
src/main/res/values-fr/strings.xml
src/main/res/values-ga/strings.xml
src/main/res/values-ta/strings.xml

This fixes #2097: translation of template keywords.
#2097
By opening this pull request, you are providing your contribution under the _Apache License 2.0_ (see [LICENSE.md](LICENSE.md)). :heavy_check_mark:

Fix crash in overeager translations

---

src/main/java/de/dennisguse/opentracks/AbstractActivity.java

Starting on Android 15, the system forces edge-to-edge rendering on all apps.
This app did account for that, so the BottomAppBar was rendering under the navbar, making it unusable.
Solution: Enable edge-to-edge rendering and apply insets to BottomAppBar and the other content.
Some tests fail, but its always inconsistent on which ones fail.
This PR resolves issues #2073 and #2103.
Solution found in [this article](https://developer.android.com/develop/ui/views/layout/edge-to-edge#java).

Enabled edge-to-edge rendering and applied navbar insets
